//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by QTImage.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_QTIMAGE_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDR_MAIN_MENU                   129
#define IDD_DIALOG1                     132
#define IDD_DIALOG_MPR                  132
#define IDD_IMAGE_SRCTRL                133
#define IDD_DIALOG_SEGMENT              134
#define IDB_BITMAP_AUTOSEG              135
#define IDB_BITMAP_BRUSH                136
#define IDB_BITMAP_CROSS                137
#define IDB_BITMAP_MANUAL               138
#define IDB_BITMAP_MESH                 139
#define IDD_SCALE_CTRL                  140
#define IDC_STATIC_GRAPH                1000
#define IDC_STATIC_CONTROL              1001
#define IDC_LIST_IMAGE                  1009
#define IDC_COMBO_OPACITY               1013
#define IDC_COMBO_COLOR                 1014
#define IDC_COMBO_GRAD                  1015
#define IDC_TEXT_PIXEL                  1016
#define IDC_TEXT_OPACITY                1017
#define IDC_SLIDER_SLICE                1018
#define IDD_IMAGE_VIEW2D                1019
#define IDD_IMAGE_CTRL2D                1020
#define IDD_IMAGE_LIST                  1021
#define IDD_IMAGE_VR                    1022
#define IDD_IMAGE_VRCTRL                1023
#define IDD_IMAGE_VRVIEW                1024
#define IDD_CONTOUR_CONFIG              1025
#define IDD_HISTOGRAM                   1026
#define IDD_PIXELEDIT                   1026
#define IDC_BTN_COLOR                   1027
#define IDD_IMAGE_SRVIEW                1027
#define IDC_STATIC_OPACITY              1028
#define IDD_IMAGE_SR                    1028
#define IDC_STATIC_COLOR                1029
#define IDD_IMAGE_SR_FRAME              1029
#define IDC_EDIT_OPACITY_PIXEL          1030
#define IDC_EDIT_OPACITY                1031
#define IDC_BTN_OPACITY                 1032
#define IDC_RADIO_MIP                   1033
#define IDC_EDIT_COLOR_PIXEL            1034
#define IDC_RADIO_COMPOSITE             1035
#define IDC_RADIO_MIP_SCALAR            1036
#define IDC_RADIO_MIP_OPACITY           1037
#define IDC_EDIT_GRAD_OPACITY_PIXEL     1038
#define IDC_EDIT_GRAD_OPACITY           1039
#define IDC_STATIC_GRAD_OPACITY         1040
#define IDC_BTN_UPDATE                  1041
#define IDC_RADIO_HARDWARE              1042
#define IDC_BTN_RESTORE                 1043
#define IDC_RADIO_SOFTWARE              1044
#define IDC_RADIO_COMP_METHOD_CLASSIFY  1045
#define IDC_RADIO_FIXPOINT              1045
#define IDC_RADIO_COMP_METHOD_INTERPOLATE 1046
#define IDC_RADIO_INTERPOLOATE_NEAREST  1047
#define IDC_RADIO_INTERPOLOATE_LINEAR   1048
#define IDC_BUTTON_GRAD                 1049
#define IDC_CHECK_SHADE                 1050
#define IDC_CHECK_GRADON                1051
#define IDC_BUTTON_LOAD                 1052
#define IDC_BUTTON_SAVE                 1053
#define IDC_STATIC_IMAGE                1054
#define IDC_CHECK_LARGEST               1056
#define IDC_SLIDER_1                    1057
#define IDC_SLIDER_2                    1058
#define IDC_STATIC_OPTION               1058
#define IDC_SLIDER_3                    1059
#define IDC_COMBO_ROI                   1059
#define IDC_SLIDER_ROI_OPACITY          1060
#define IDC_BUTTON_ADDROI               1061
#define IDC_EDIT_ROINAME                1062
#define IDC_BUTTON_CROSS                1063
#define IDC_BUTTON_MANUAL_SEG           1064
#define IDC_SLIDER1                     1064
#define IDC_BUTTON_BRUSH_SEG            1065
#define IDC_EDIT_VALUE                  1065
#define IDC_BUTTON_AUTO_SEG             1066
#define IDC_STATIC_TEXT                 1066
#define IDC_BUTTON_MESH                 1067
#define IDC_BUTTON_APPLY                1068
#define IDC_COMBO_METHOD                1069
#define IDC_STATIC_ALGORITHM            1070
#define IDC_STATIC_LOG                  1071
#define IDC_STATIC_BTN_BOX              1072
#define IDC_BUTTON_UPDATE               1073
#define IDC_SLIDER_LOD                  1074
#define IDC_STATIC_PIXEL                1076
#define IDM_FILE_IMPORT_SERIES          32771
#define IDM_FILE_EXIT                   32772
#define ID_VIEW3D_VOL_RENDER            32773
#define ID_VIEW3D_GROUND_COLOR          32774
#define ID_VIEW2D_GROUND_COLOR          32775
#define IDM_FILE_SAVE_SERIES            32776
#define ID_VIEW2D_RESET_WINDOWLEVEL     32777
#define ID_VIEW2D_CONTOURLINE           32778
#define ID_EDIT_HISTOGRAM               32779
#define ID_EDIT_PIXELEDIT               32779
#define ID_VIEW2D_MPR                   32780
#define ID_ROI_SEGMENT                  32781
#define ID_VIEW3D_DELAUNAY              32784
#define ID_VIEW3D_POWERCRUST            32785
#define ID_VIEW3D_SOLID_SURFACE         32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
