//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TreeList.rc
//
#define IDC_REGMORE                     2
#define IDD_ABOUTBOX                    100
#define ID_DELAYTIMER                   101
#define IDD_OPTIONSDIALOG               102
#define IDD_ENDDIALOG                   103
#define IDR_POPUPMENU                   104
#define IDD_FIND_FILES                  110
#define IDD_REGISTER2                   111
#define IDD_RESULTSBOX                  112
#define IDR_MAINFRAME                   128
#define IDR_TREELISTTYPE                129
#define IDC_USER_NAME                   138
#define IDC_USER_CODE                   139
#define IDB_REMOVE                      200
#define IDB_FIXED                       201
#define IDB_REMOTE                      202
#define IDB_CD                          203
#define IDB_DESKTOP                     204
#define IDB_FOLDCLS                     205
#define IDB_FOLDOPEN                    206
#define IDB_DOC                         207
#define IDC_RES_STRING1                 1000
#define IDC_RES_STRING2                 1001
#define IDC_RES_STRING3                 1002
#define IDC_RES_STRING4                 1003
#define IDC_RADIONUMTYPE                1010
#define IDC_RADIO2                      1011
#define IDC_RADIO3                      1012
#define IDC_CHECK_SOUND                 1013
#define IDC_SHOW_UNUSED                 1014
#define IDC_SHOW_UNUSED_BLACK           1015
#define IDC_FILES_PATH                  1029
#define ID_MY_SCAN_DISK                 1030
#define ID_SETTINGS                     32771
#define ID_ADJUST_DATA                  32773
#define ID_RESCAN                       32774
#define ID_SAVE_RESULTS                 32776
#define ID_REGISTER                     32777
#define ID_RESULTS                      32778
#define ID_SHOW_RESULTS                 32779
#define ID_REFRESH                      32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
