//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Wzd.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WZD_DIALOG                  102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDC_COMBO1                      1000
#define IDC_BUTTON1                     1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON3                     1003
#define IDC_RADIO1                      1004
#define IDC_RADIO2                      1005
#define IDC_RADIO3                      1006
#define IDC_EDIT1                       1007
#define IDC_CHECK1                      1009
#define IDC_CHECK2                      1010
#define IDC_STATUSBAR_STATIC            1011
#define IDC_TOOLBAR_STATIC              1012
#define ID_FILE_EXIT                    32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
