//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Observer.rc
//
#define IDPREVIOUS                      4
#define IDNEXT                          5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_FONT                        125
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ObserverTYPE                130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDB_CHART                       176
#define IDB_CHART_DESIGN                180
#define IDB_CHART_DESIGNLARGE           181
#define IDB_CHART_LAYOUT                182
#define IDB_CHART_LAYOUTLARGE           183
#define IDB_CHART_FORMAT                184
#define ID_VIEW_NAVIGATION              185
#define IDB_CHART_FORMATLARGE           185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_EDIT_MENU                   306
#define IDB_TREESMALL                   310
#define IDB_CHART_MENU                  311
#define IDR_MENU1                       311
#define IDR_CHARTTITLE                  312
#define IDB_CHART_DESIGN16              313
#define IDR_CHART_GRADIENT              314
#define IDR_CHART_OUTLINESTYLE          315
#define IDR_CHART_FILLHATCHING          316
#define IDR_CHART_ALIGNMENT             317
#define IDR_CHART_DOCKING               318
#define IDB_ANALYZE16                   319
#define IDB_ANALYZE                     320
#define IDB_COMPARE                     321
#define IDR_MENU_RIBBON_ACTIVITY1       322
#define IDR_MENU_RIBBON_ACTIVITY2       323
#define IDB_SUPPORT                     323
#define IDB_SUPPORT16                   324
#define IDB_EXPORT                      325
#define IDB_EXPORT16                    326
#define IDR_AXISTITLES                  327
#define IDR_AXIS                        328
#define IDR_OUTLINE_WIDTH               329
#define IDR_MENU2                       330
#define IDR_CHART_PALETTE               330
#define IDD_SHOWSERIALKEYDLG            331
#define IDD_TIPOFTHEDAYDLG              332
#define IDD_ACTIVATEPRODUCTDLG          333
#define IDD_SETDESCRIPTIONDLG           334
#define IDC_EXPLORER1                   1000
#define IDC_EDIT1                       1000
#define IDC_LICENCE                     1001
#define IDC_BUTTON2                     1002
#define IDC_WEBSITE                     1002
#define ID_CHECK1                       1016
#define WM_ANALYSIS_SINGLEACTIVITY_WITHALLTASKS_STACKED 1433
#define WM_ANALYSIS_SINGLEACTIVITY_WITHALLTASKS_TOTAL 1434
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_PAGELAYOUT_EFFECTS_ACADEMIC  32770
#define ID_NONE                         32771
#define ID_CHARTTITLE_NONE              32772
#define ID_SHOWOUTSIDECHARTAREA         32773
#define ID_PAGELAYOUT_TEXTWRAPPING_BEHINDTEXT 32774
#define ID_CHARTTITLE_SHOWOUTSIDE       32774
#define ID_PAGELAYOUT_BRINGFORWARD      32775
#define ID_DOCKINSIDECHARTAREA          32775
#define ID_PAGELAYOUT_BRINGINFRONTOFTEXT 32776
#define ID_CHARTTITLE_DOCKTOAREA        32776
#define ID_PAGELAYOUT_BRINGTOFRONT      32777
#define ID_GRADIENT_NONE                32777
#define ID_GRADIENT_LEFTRIGHT           32778
#define ID_GRADIENT_TOPBOTTOM           32779
#define ID_GRADIENT_CENTER              32780
#define ID_GRADIENT_DIAGONALLEFT        32781
#define ID_GRADIENT_DIAGONALRIGHT       32782
#define ID_GRADIENT_HORIZONTALCENTER    32783
#define ID_GRADIENT_VERTICALCENTER      32784
#define ID_NONE32777                    32785
#define ID_LEFTRIGHT                    32786
#define ID_TOPBOTTOM                    32787
#define ID_FONT_CHANGECASE              32787
#define ID_DIAGONALRIGHT                32787
#define ID_CENTER                       32788
#define ID_DIAGONALLEFT                 32789
#define ID_HORIZONTALCENTER             32789
#define ID_FONT_BOLD                    32790
#define ID_VERTICALCENTER               32791
#define ID_FONT_ITALIC                  32793
#define ID_NOTSET                       32793
#define ID_FONT_STRIKETHROUGH           32795
#define ID_DASH                         32795
#define ID_FONT_SUBSCRIPT               32796
#define ID_FONT_SUPERSCRIPT             32797
#define ID_DASHDOT                      32797
#define ID_FONT_UNDERLINE               32799
#define ID_DASHDOTDOT                   32799
#define ID_DOT                          32801
#define ID_SOLID                        32803
#define ID_NONE32805                    32805
#define ID_BACKWARDDIAGONAL             32807
#define ID_HATCHING_BACKWARDDIAGONAL    32808
#define ID_CROSS                        32809
#define ID_ALIGN_MIDDLECENTER           32811
#define ID_ALIGN_TOPLEFT                32812
#define ID_ALIGN_TOPCENTER              32813
#define ID_ALIGN_TOPRIGHT               32814
#define ID_ALIGN_MIDDLELEFT             32815
#define ID_ALIGN_MIDDLERIGHT            32816
#define ID_ALIGN_BOTTOMCENTER           32817
#define ID_ALIGN_BOTTOMLEFT             32818
#define ID_ALIGN_BOTTOMRIGHT            32819
#define ID_MIDDLECENTER                 32820
#define ID_TOPLEFT                      32821
#define ID_TOPCENTER                    32822
#define ID_TOPRIGHT                     32823
#define ID_MIDDLELEFT                   32824
#define ID_MIDDLERIGHT                  32825
#define ID_BOTTOMCENTER                 32826
#define ID_BOTTOMLEFT                   32827
#define ID_BOTTOMRIGHT                  32828
#define ID_CHART_DOCK_TOP               32829
#define ID_CHART_DOCK_LEFT              32830
#define ID_CHART_DOCK_RIGHT             32831
#define ID_CHART_DOCK_BOTTOM            32832
#define ID_TOP                          32833
#define ID_LEFT                         32834
#define ID_RIGHT                        32835
#define ID_BOTTOM                       32836
#define ID_ALLTASKS                     32837
#define ID_XAXIS_SHOW                   32840
#define ID_XAXIS_DONOTSHOW              32841
#define ID_YAXIS_SHOW                   32842
#define ID_YAXIS_DONOTSHOW              32843
#define ID_XAXIS_SHOW32844              32844
#define ID_XAXIS_DONOTSHOW32845         32845
#define ID_YAXIS_SHOW32846              32846
#define ID_YAXIS_DONOTSHOW32847         32847
#define ID_AXIS_XAXIS_SHOW              32848
#define ID_AXIS_XAXIS_DONOTSHOW         32849
#define ID_AXIS_YAXIS_SHOW              32850
#define ID_AXIS_YAXIS_DONOTSHOW         32851
#define ID_DIVOT                        32852
#define ID_HATCHING_NONE                32853
#define ID_HATCHING_CROSS               32854
#define ID_HORIZONTAL                   32854
#define ID_HATCHING_DIVOT               32855
#define ID_HATCHING_HORIZONTAL          32856
#define ID_VERTICAL                     32856
#define ID_HATCHING_VERTICAL            32857
#define ID_OUTLINE_WIDTH_1              32858
#define ID_OUTLINE_WIDTH_2              32859
#define ID_OUTLINE_WIDTH_3              32860
#define ID_OUTLINE_WIDTH_4              32861
#define ID_1                            32862
#define ID_2                            32863
#define ID_3                            32864
#define ID_4                            32865
#define ID_OUTLINE_WIDTH                32866
#define ID_PALETTE_GRAYSCALE            32868
#define ID_PALETTE_EXCEL                32869
#define ID_PALETTE_LIGHT                32870
#define ID_PALETTE_PASTEL               32871
#define ID_PALETTE_EARTHTONES           32872
#define ID_PALETTE_SEMITRANSPARENT      32873
#define ID_PALETTE_BERRY                32874
#define ID_PALETTE_CHOCOLATE            32875
#define ID_PALETTE_FIRE                 32876
#define ID_PAGELAYOUT_EFFECTS_OFFICE    32892
#define ID_PAGELAYOUT_COLUMNS_ONE       32893
#define ID_PAGELAYOUT_ARRANGE_ALIGN     32894
#define ID_PAGELAYOUT_ARRANGE_BRINGTOFRONT 32895
#define ID_PAGELAYOUT_ARRANGE_GROUP     32896
#define ID_PAGELAYOUT_ARRANGE_POSITION  32897
#define ID_PAGELAYOUT_ARRANGE_ROTATE    32898
#define ID_PAGELAYOUT_ARRANGE_SENDTOBACK 32899
#define ID_PAGELAYOUT_ARRANGE_TEXTWRAPPING 32900
#define ID_PAGELAYOUT_PAGEBACKGROUND_PAGEBORDERS 32901
#define ID_PAGELAYOUT_PAGEBACKGROUND_PAGECOLOR 32902
#define ID_PAGELAYOUT_PAGEBACKGROUND_WATERMARK 32903
#define ID_PAGELAYOUT_PAGESETUP_BREAKS  32904
#define ID_PAGELAYOUT_PAGESETUP_COLUMNS 32905
#define ID_PAGELAYOUT_PAGESETUP_HYPHENATION 32906
#define ID_PAGELAYOUT_PAGESETUP_LINENUMBERS 32907
#define ID_PAGELAYOUT_PAGESETUP_MARGINS 32908
#define ID_PAGELAYOUT_PAGESETUP_ORIENTATTION 32909
#define ID_PAGELAYOUT_PAGESETUP_SIZE    32910
#define ID_PAGELAYOUT_FONTS             32913
#define ID_PAGELAYOUT_SENDBACKWARD      32968
#define ID_PAGELAYOUT_SENDBEHINDTEXT    32969
#define ID_PAGELAYOUT_SENDTOBACK        32970
#define ID_PAGELAYOUT_TEXTWRAPPING_SQUARE 32972
#define ID_PAGELAYOUT_TEXTWRAPPING_THROUGH 32978
#define ID_PAGELAYOUT_TEXTWRAPPING_TIGHT 32979
#define ID_PAGELAYOUT_TEXTWRAPPING_TOPANDBOTTOM 32981
#define ID_PAGELAYOUT_TEXTWRAPPING_EDITWRAPPOINTS 33024
#define ID_CHART_DESIGN_TYPE_CHANGE     33039
#define ID_CHART_DESIGN_TYPE_SAVETEMPLATE 33040
#define ID_CHART_DESIGN_DATA_SWITCH     33041
#define ID_CHART_DESIGN_DATA_EDIT       33042
#define ID_CHART_DESIGN_DATA_SHOW       33043
#define ID_CHART_LAYOUT_SHAPES_PICTURE  33044
#define ID_CHART_LAYOUT_SHAPES_SHAPES   33045
#define ID_CHART_LAYOUT_SHAPES_TEXTBOX  33046
#define ID_CHART_LAYOUT_LABELS_TITLE    33047
#define ID_CHART_LAYOUT_LABELS_AXIS     33048
#define ID_CHART_LAYOUT_LABELS_LEGEND   33049
#define ID_CHART_LAYOUT_LABELS_DATALABELS 33050
#define ID_CHART_LAYOUT_LABELS_DATATABLE 33051
#define ID_CHART_LAYOUT_AXES_AXES       33052
#define ID_CHART_LAYOUT_AXES_GRIDLINES  33053
#define ID_CHART_FORMAT_CURSEL_FORMAT   33054
#define ID_CHART_FORMAT_CURSEL_RESET    33055
#define ID_CHART_FORMAT_SHAPES_FILL     33056
#define ID_CHART_FORMAT_SHAPES_OUTLINE  33057
#define ID_CHART_FORMAT_SHAPES_EFFECTS  33058
#define ID_PAGELAYOUT_TEXTWRAPPING      33090
#define ID_PAGELAYOUT_TEXTWRAPPING_INFRONTOFTEXT 33095
#define ID_PAGELAYOUT_TEXTWRAPPING_INLINEWITHTEXT 33096
#define ID_OUTLINESTYLE_NOTSET          33100
#define ID_OUTLINESTYLE_DASH            33101
#define ID_OUTLINESTYLE_DASHDOT         33102
#define ID_OUTLINESTYLE_DASHDOTDOT      33103
#define ID_OUTLINESTYLE_DOT             33104
#define ID_OUTLINESTYLE_SOLID           33105
#define ID_FROM_PALETTE_POSITION        33120
#define ID_PAGELAYOUT_MORELAYOUTOPTIONS 33125
#define ID_PAGELAYOUT_THEMES_MORETHEMES 33208

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         32885
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           335
#endif
#endif
