// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_hscroll.h"

/////////////////////////////////////////////////////////////////////////////
// C_HScroll

IMPLEMENT_DYNCREATE(C_HScroll, CWnd)

/////////////////////////////////////////////////////////////////////////////
// C_HScroll properties

/////////////////////////////////////////////////////////////////////////////
// C_HScroll operations

CString C_HScroll::GetLargeChange()
{
	CString result;
	InvokeHelper(0x68030003, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void C_HScroll::SetLargeChange(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x68030003, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

short C_HScroll::GetValue()
{
	short result;
	InvokeHelper(0x68030002, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void C_HScroll::SetValue(short nNewValue)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x68030002, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}
