#if !defined(AFX__VSCROLL_H__528D8295_BD5B_4373_83C9_3783A4A702F1__INCLUDED_)
#define AFX__VSCROLL_H__528D8295_BD5B_4373_83C9_3783A4A702F1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_VScroll wrapper class

class C_VScroll : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_VScroll)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x83f9408c, 0x91b9, 0x420e, { 0xa6, 0x42, 0x64, 0xcd, 0x20, 0x6a, 0xa1, 0xeb } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetLargeChange();
	void SetLargeChange(LPCTSTR lpszNewValue);
	short GetValue();
	void SetValue(short nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__VSCROLL_H__528D8295_BD5B_4373_83C9_3783A4A702F1__INCLUDED_)
