#if !defined(AFX__XPCMDBUTTON_H__3792E7B6_0D1B_4C9D_86D5_2C75FDBF3915__INCLUDED_)
#define AFX__XPCMDBUTTON_H__3792E7B6_0D1B_4C9D_86D5_2C75FDBF3915__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// C_xpcmdbutton wrapper class

class C_xpcmdbutton : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_xpcmdbutton)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x9076b41a, 0xf995, 0x44da, { 0x9b, 0x9f, 0x86, 0x1, 0x25, 0x5c, 0x7d, 0x48 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	long GetState();
	void SetState(long nNewValue);
	CString GetCaption();
	void SetCaption(LPCTSTR lpszNewValue);
	COleFont GetFont();
	void SetRefFont(LPDISPATCH newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__XPCMDBUTTON_H__3792E7B6_0D1B_4C9D_86D5_2C75FDBF3915__INCLUDED_)
