ChartContainerLib: C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/ChartsXMLSerializer.h File Reference
ChartsXMLSerializer.h File Reference
#include "ChartDef.h"
Classes
class CChartsXMLSerializer
Functions
template<typename T >
void get_attrValue (_bstr_t attrName, MSXML2::IXMLDOMNamedNodeMap *pAttrMap, T &val)
template<>
void get_attrValue< string_t > (_bstr_t attrName, MSXML2::IXMLDOMNamedNodeMap *pAttrMap, string_t &val)
Function Documentation
template<typename T > void get_attrValue (_bstr_t attrName, MSXML2::IXMLDOMNamedNodeMap * pAttrMap, T & val) inline
Definition at line 14 of file ChartsXMLSerializer.h.
Referenced by CChartsXMLSerializer::GetChartNamesFromXMLFile(), CChartsXMLSerializer::ReplaceChartsFromXMLFile(), and CChartsXMLSerializer::XMLToCharts().
template<> void get_attrValue< string_t > (_bstr_t attrName, MSXML2::IXMLDOMNamedNodeMap * pAttrMap, string_t & val) inline
Definition at line 32 of file ChartsXMLSerializer.h.