ChartContainerLib: C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/Util.cpp File Reference
Util.cpp File Reference
#include "stdafx.h"
#include "util.h"
Functions
string_t NormalizeString (string_t str, size_t maxLen, TCHAR delim)
void CreateRoundedRect (GraphicsPath &grPath, RectF &rectF, float radius, bool bReset)
Function Documentation
void CreateRoundedRect (GraphicsPath & grPath, RectF & rectF, float radius, bool bReset)
Definition at line 32 of file Util.cpp.
Referenced by CPageCtrl::DrawArrow(), CDataWnd::DrawDataWnd(), and CDataWnd::OnPaint().
string_t NormalizeString (string_t str, size_t maxLen, TCHAR delim)
Definition at line 15 of file Util.cpp.
Referenced by CChartContainer::AddChart(), CChartContainer::ChangeChartName(), CChartContainer::ChangeChartYValName(), and CChartContainer::SetAxisXName().