ChartContainerLib: C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/Util.h File Reference
Util.h File Reference
Classes
class PointT< T >
struct coord_in_range< T, bY >
struct coord_in_range< T, false >
struct less_pnt< T, bY >
struct less_pnt< T, false >
struct equal_coord< T, bY >
struct equal_coord< T, false >
struct greater_or_equal< T, bY >
struct greater_or_equal< T, false >
struct in_vicinity< T >
struct lesser_adjacent_interval< Pnt, bY >
struct lesser_adjacent_interval< Pnt, false >
struct time_series_to_pnt< T >
struct xy_to_pnt< T >
struct get_map_value< T1, T2 >
struct count_in_range< T, bY >
struct count_in_range< T, false >
struct nearest_to< T, bY >
struct nearest_to< T, false >
struct nmb_to_string< T, bY >
struct nmb_to_string< T, false >
struct not_inside_range< T, bY >
struct not_inside_range< T, false >
struct get_max_str< T, Idx >
struct get_max_str< string_t, Idx >
Typedefs
typedef std::basic_string< TCHAR > string_t
typedef
std::basic_stringstream< TCHAR > sstream_t
Functions
string_t NormalizeString (string_t str, size_t maxLen, TCHAR delim)
template<typename T >
bool in_range (const T &lL, const T &rL, const T &val)
Rect CRectToGdiRect (CRect &rect)
RectF CRectToGdiRectF (CRect &rect)
CRect RectFToCRect (RectF &rectF)
In client coord.
RectF GdiRectToRectF (Rect rect)
RectF RectFFromCenterF (const PointF pntCenterF, float fWidth, float fHeight)
PointF GetRectFCenterF (const RectF rectF)
CPoint CPointFromPntF (PointF pntF)
void CreateRoundedRect (GraphicsPath &grPath, RectF &rectF, float radius, bool bReset)
Color SetAlpha (const Color color, int alpha)
template<class _InIt , class _Pr >
_InIt find_nearest (_InIt _First, _InIt _Last, _Pr _Pred)
template<class _InIt , class _Pr >
std::pair< _InIt, _InIt > find_border_pnts (_InIt _First, _InIt _Last, _Pr _Pred)
Typedef Documentation
typedef std::basic_stringstream<TCHAR> sstream_t
Definition at line 16 of file Util.h.
typedef std::basic_string<TCHAR> string_t
Definition at line 15 of file Util.h.
Function Documentation
CPoint CPointFromPntF (PointF pntF) inline
Definition at line 73 of file Util.h.
Referenced by CChartContainer::SetZoomBorderColor(), CChartContainer::ShowDataLegend(), and CChartContainer::UpdateDataLegend().
void CreateRoundedRect (GraphicsPath & grPath, RectF & rectF, float radius, bool bReset)
Definition at line 32 of file Util.cpp.
Referenced by CPageCtrl::DrawArrow(), CDataWnd::DrawDataWnd(), and CDataWnd::OnPaint().
Rect CRectToGdiRect (CRect & rect) inline
Definition at line 31 of file Util.h.
Referenced by CChartContainer::SaveContainerImage().
RectF CRectToGdiRectF (CRect & rect) inline
Definition at line 36 of file Util.h.
Referenced by CDataWnd::DrawDataWnd().
template<class _InIt , class _Pr > std::pair<_InIt, _InIt> find_border_pnts (_InIt _First, _InIt _Last, _Pr _Pred) inline
Definition at line 492 of file Util.h.
Referenced by CChart::GetStartEndDataIterators(), and CChartContainer::ReplaceChartData().
template<class _InIt , class _Pr > _InIt find_nearest (_InIt _First, _InIt _Last, _Pr _Pred) inline
Definition at line 473 of file Util.h.
Referenced by CChart::GetNearestPointD().
RectF GdiRectToRectF (Rect rect) inline
Definition at line 51 of file Util.h.
Referenced by CChartContainer::DrawContainerToBmp(), CDataWnd::OnPaint(), and CChartContainer::OnPaint().
PointF GetRectFCenterF (const RectF rectF) inline
Definition at line 65 of file Util.h.
Referenced by CPageCtrl::DrawArrow().
template<typename T > bool in_range (const T & lL, const T & rL, const T & val)
Definition at line 23 of file Util.h.
Referenced by CChartDataView::DataItemFromMousePnt(), CChartContainer::DrawSelPntsD(), CChartContainer::HasVisiblePntsDInYBand(), CChartContainer::PrepareDataLegend(), CChartDataView::RefreshSelCells(), CChartDataView::RowRectFromDataID(), CChartContainer::SetChartTension(), CChartDataView::UpdateDataIdx(), CChartContainer::UpdateDataLegend(), and CChartContainer::ZoomMoveContainerX().
string_t NormalizeString (string_t str, size_t maxLen, TCHAR delim)
Definition at line 15 of file Util.cpp.
Referenced by CChartContainer::AddChart(), CChartContainer::ChangeChartName(), CChartContainer::ChangeChartYValName(), and CChartContainer::SetAxisXName().
RectF RectFFromCenterF (const PointF pntCenterF, float fWidth, float fHeight) inline
Definition at line 57 of file Util.h.
Referenced by CChart::DrawChartCurve(), CChartContainer::DrawDataViewPntsD(), and CChartContainer::DrawSelPntsD().
CRect RectFToCRect (RectF & rectF) inline
In client coord.
Definition at line 42 of file Util.h.
Referenced by CDataWnd::CalcLabelStrRect().
Color SetAlpha (const Color color, int alpha) inline
Definition at line 85 of file Util.h.
Referenced by CChart::DrawChartCurve(), CChart::GetSelValString(), CChartContainer::GetSelValString(), and CChart::GetVisibleChartNameAndVisuals().