ChartContainerLib: CChartContainer Class Reference
CChartContainer Class Reference
#include <ChartContainer.h>
Public Member Functions
CChartContainer (string_t name=string_t(_T("")))
virtual ~CChartContainer ()
CChartContainer & operator= (const CChartContainer &rhs)
bool CreateChartCtrlWnd (DWORD dwExStyle, DWORD dwStyle, const CRect &wndRect, CWnd *pParent, UINT nID)
CChartContainer * CloneChartContainer (string_t name=string_t(_T("")), bool bCloneState=false)
Color GetBkColor (void) const
Color GetBorderColor (void) const
Color GetAxesColor (void) const
Color GetZoomBorderColor (void) const
Color GetLegPntsColor (void) const
Color GetDataViewPntsColor (void) const
Color GetLegBkgndColor (void) const
Color GetLegBorderColor (void) const
Color GetGridColor (void) const
void SetBkColor (Color col, bool bRedraw=false)
void SetBorderColor (Color col, bool bRedraw=false)
void SetAxesColor (Color col, bool bRedraw=false)
void SetZoomBorderColor (Color col)
void SetLegPntsColor (Color col, bool bRedraw=false)
void SetDataViewPntsColor (Color col, bool bRedraw=false)
void SetLegBkgndColor (Color col, bool bRedraw=false)
void SetLegBorderColor (Color col, bool bRedraw=false)
void SetGridColor (Color col, bool bRedraw=false)
double GetStartX (void) const
double GetEndX (void) const
double GetInitialStartX (void) const
double GetInitialEndX (void) const
double GetInitialMinExtY (void) const
double GetInitialMaxExtY (void) const
double GetMinY (void) const
double GetMaxY (void) const
double GetScX (void) const
double GetScY (void) const
bool IsUserEnabled (void) const
void EnableUser (bool bEnable, bool bClearState=true)
bool HasNamesLeg (void) const
void SetNamesLegFlag (bool bHasNamesLeg)
void UpdateExtX (double minExtX, double maxExtX, bool bRedraw=false)
void UpdateExtY (double minExtY, double maxExtY, bool bRedraw=false)
PAIR_DBLS SetExtX (bool bRedraw=false)
PAIR_DBLS SetExtY (bool bRedraw=false)
int GetContainerPrecisionX (void) const
void SetContainerPrecision (int precision, bool bRedraw=false)
int GetDataViewChartIdx (void) const
void SetDataViewChartIdx (int chartIdx)
const MAP_SELPNTSD * GetDataViewSelPntsD (void) const
size_t SetDataViewSelPnts (int chartIdx, const MAP_SELPNTSD &mapSelPntsD, V_CHARTDATAD *pChartData=NULL)
bool ClearDataViewChartIdx (void)
string_t GetContainerName (void) const
void SetContainerName (string_t name)
string_t GetAxisXName (void) const
void SetAxisXName (string_t nameX, bool bRedraw=false)
val_label_str_fn GetLabXValStrFnPtr (void) const
void SetLabXValStrFn (val_label_str_fn pLabValStrFn, bool bRedraw=false)
bool IsContainerEmpty (void) const
bool HasChartWithData (int chartIdx, bool bVisibleOnly=false) const
int HasChartDifferentPnts (int chartIdx, bool bVisibleOnly=false) const
bool HasVisiblePntsDInYBand (int chartIdx, double minY, double maxY)
size_t GetContainerSize (void) const
MAP_CHARTS * GetMapCharts (void)
MAP_CHARTS::iterator GetFirstChart (void)
MAP_CHARTS::const_iterator GetFirstChart (void) const
MAP_CHARTS::iterator GetChartsEnd (void)
MAP_CHARTS::const_iterator GetChartsEnd (void) const
MAP_CHARTS::iterator FindChart (int chartIdx)
MAP_CHARTS::const_iterator FindChart (int chartIdx) const
V_HIST & GetContainerHistory (bool bY=false)
size_t CopyHistory (V_HIST &vHistDst, const V_HIST &vHistSrc) const
MatrixD * GetTransformMatrixD (void) const
PAIR_DBLS GetMinMaxExtX (void) const
PAIR_DBLS GetMinMaxExtY (void) const
void UndoHistStepX (bool bRedraw=false)
bool UnwindHistX (double minX, double maxX)
void UndoHistStepY (bool bRedraw=false)
void OnChangedSize (int cx, int cy)
void RefreshWnd (void)
Status SaveContainerImage (string_t pathName=string_t(_T("")))
HRESULT SaveChartData (string_t pathName, bool bAll=false)
HRESULT LoadCharts (LPCTSTR fileName, const MAP_CHARTCOLS &mapContent, bool bClearCharts=false)
HRESULT ReplaceContainerCharts (LPCTSTR fileName)
HRESULT GetChartNamesFromXMLFile (LPCTSTR fileName, MAP_CHARTCOLS &mapContent)
HRESULT GetChartNamesFromXMLFile (LPCTSTR fileName, MAP_NAMES &mapNames)
bool ExportChartData (string_t chartName, V_CHARTDATAD &vDataPnts) const
bool ExportChartData (string_t chartName, std::vector< std::pair< double, double > > &vPairs) const
bool ExportChartData (string_t chartName, std::vector< double > &vX, std::vector< double > &vY) const
std::tuple< double, double, bool > GetChartBoundaries (int chartIdx, bool bY=false) const
bool IsChartVisible (int chartIdx) const
bool SetChartVisibility (int chartIdx, bool bVisible, bool bRedraw=false)
int ToggleChartVisibility (int chartIdx)
std::pair< float, bool > GetChartPenWidth (int chartIdx) const
bool UpdateChartPenWidth (int chartIdx, float penWidth, bool bVisibleOnly, bool bRedraw=false)
std::pair< float, bool > GetChartTension (int chartIdx) const
bool SetChartTension (int chartIdx, float tension, bool bVisibleOnly, bool bRedraw=false)
std::pair< bool, bool > AreChartPntsAllowed (int chartIdx) const
bool AllowChartPnts (int chartIdx, bool bAllowed, bool bVisibleOnly, bool bRedraw=false)
std::pair< Color, bool > GetChartColor (int chartIdx) const
bool SetChartColor (int chartIdx, Color col, bool bVisibleOnly, bool bRedraw=false)
std::pair< DashStyle, bool > GetChartDashStyle (int chartIdx) const
bool SetChartDashStyle (int chartIdx, DashStyle dashStyle, bool bVisibleOnly, bool bRedraw=false)
int HasSelectedChart (void) const
int SelectChart (int chartIdx, bool bRedraw=false)
int SelectChartByMouseClick (CPoint pnt, bool bRedtaw=false)
int GetChartPrecisionY (int chartIdx) const
bool SetChartPrecisionY (int chartIdx, int precisionY, bool bVisibleOnly, bool bRedraw=false)
string_t GetChartName (int chartIdx) const
bool ChangeChartName (int chartIdx, string_t name, bool bRedraw=false)
string_t GetChartYValName (int chartIdx) const
bool ChangeChartYValName (int chartIdx, string_t nameY, bool bVisibleOnly, bool bRedraw=false)
val_label_str_fn GetLabYValStrFnPtr (int chartIdx) const
bool SetLabYValStrFn (int chartIdx, val_label_str_fn m_pLabYValStrFn, bool bVisibleOnly, bool bRedraw=false)
V_CHARTDATAD * GetChartData (int chartIdx)
int GetChartIdx (string_t chartName) const
std::pair< double, bool > GetChartLocScaleY (int chartIdx) const
bool UpdateChartLocScaleY (int chartIdx, double locScY, bool bVisibleOnly, bool bRedraw=false)
bool ZoomMoveContainerX (double startX, double endX, bool bRedraw)
bool ZoomMoveContainerY (double startY, double endY, bool bMoving, bool bRedraw)
int AddChart (bool bVisible, bool bShowPnts, string_t label, string_t labelY, int precisionY, DashStyle dashStyle, float penWidth, float tension, Color colChart, V_CHARTDATAD &vData, bool bRedraw=false)
int AddChart (bool bVisible, bool bShowPnts, string_t label, string_t labelY, int precisionY, DashStyle dashStyle, float penWidth, float tension, Color colChart, std::vector< double > &vTmSeries, double startX=0.0, double stepX=1.0, bool bRedraw=false)
int AddChart (bool bVisible, bool bShowPnts, string_t label, string_t labelY, int precisionY, DashStyle dashStyle, float penWidth, float tension, Color colChart, std::vector< std::pair< double, double > > &vXYData, bool bRedraw=false)
int AddChart (bool bVisible, bool bShowPnts, string_t label, string_t labelY, int precisionY, DashStyle dashStyle, float penWidth, float tension, Color colChart, std::vector< double > &vX, std::vector< double > &vY, bool bRedraw=false)
bool AppendChartData (int chartIdx, V_CHARTDATAD &vData, bool bUpdate=false)
bool AppendChartData (int chartIdx, std::vector< double > &vTmSeries, double startX=0.0, double stepX=1.0, bool bUpdate=false)
bool AppendChartData (int chartIdx, std::vector< std::pair< double, double > > &vXYData, bool bUpdate=false)
bool AppendChartData (int chartIdx, std::vector< double > &vX, std::vector< double > &vY, bool bUpdate=false)
bool ReplaceChartData (int chartIdx, V_CHARTDATAD &vData, bool bClip=false, bool bUpdate=false, bool bVerbose=false, bool bRedraw=false)
bool ReplaceChartData (int chartIdx, std::vector< double > &vTmSeries, double startX=0.0, double stepX=1.0, bool bClip=false, bool bUpdate=false, bool bVerbose=false, bool bRedraw=false)
bool ReplaceChartData (int chartIdx, std::vector< std::pair< double, double > > &vXYData, bool bClip=false, bool bUpdate=false, bool bVerbose=false, bool bRedraw=false)
bool ReplaceChartData (int chartIdx, std::vector< double > &vX, std::vector< double > &vY, bool bClip=false, bool bUpdate=false, bool bVerbose=false, bool bRedraw=false)
void ResetCharts (bool bResetLocY=false)
void ResetChartContainer (bool bKeepCharts=false, bool bResetCols=false)
bool TruncateChart (int chartIdx, double startX, double endX, bool bUpdateExt=false, bool bRedraw=false)
bool RemoveChart (int chartIdx, bool bCorrectMinMax, bool bRedraw)
void UpdateDataViewPnts (int chartIdx, size_t dataID, PointD dataPntD, bool bAdd)
void UpdateDataViewPnts (int chartIdx, const MAP_SELPNTSD &mapSelPntsD)
void EqualizeVertRanges (double spaceMult, bool bRedraw=false)
PointD GetDataLegPntD (void) const
bool IsLabWndVisible (bool bLeg) const
bool IsLabWndExist (bool bLeg) const
bool ShowAxisXBoundaries (bool bSet, bool bRedraw=false)
CDataWnd * ShowDataLegend (double dataLegX)
CDataWnd * ShowNamesLegend (void)
bool ShowChartPoints (int chartIdx, bool bShow, bool bRedraw=false)
CDataWnd * DestroyLabWnd (CDataWnd *pDataWnd, bool bRedraw=true)
bool HideLabWnds (bool bRedraw=false)
CChartDataView * DestroyChartDataView (void)
bool ShowDataView (const string_t &szChartName, bool bRefresh)
void UpdateContainerWnds (int chartIdx=-1, bool bMatrix=false, DATAVIEW_FLAGS dataChange=F_NODATACHANGE)
int GetMaxChartIdx (void) const
float GetAxisOffsetX (void) const
Static Public Member Functions
static void PrintCharts (CChartContainer *pContainer, int scrDpiX, HDC printDC)
Protected Member Functions
CChart * CloneChart (int chartIdx, bool bCloneState=false)
CH_MODE GetChModeX (void) const
CH_MODE GetChModeY (void) const
MatrixD * GetTransformMatrixD (double startX, double endX, double minY, double maxY)
void SetTransformMatrixD (MatrixD *pMatrixD)
void SetTransformMatrixD (void)
CChart * GetVisibleChart (int chartIdx) const
CChart * GetChart (int chartIdx, bool bVisibleOnly=false) const
CChart * FindChartByName (string_t nameStr) const
CH_MODE ZoomContainerX (double startX, double endX, bool bRedraw=false)
CH_MODE MoveContainerChartsX (double deltaX, bool bRedraw=false)
CH_MODE ZoomContainerY (double startY, double endY, bool bRedraw=false)
CH_MODE MoveContainerChartsY (double deltaY, bool bRedraw=false)
LRESULT SendNotification (UINT code, int chartIdx=-1)
CDataWnd * ShowDataLegend (CPoint pnt)
void UpdateDataLegend (bool bChangeMatrix)
void CopyDataLegendWnd (void)
void MousePntToPntD (CPoint pnt, PointD &dataPntD, MatrixD *pMatrixD, double locScY=1.0)
double UpdateScaleX (const float drawRectWidth, double startX, double endX)
double UpdateScaleY (const float drawRectHeight, double minY, double maxY)
std::pair< double, double > UpdateScales (const RectF drawRectF, double minX, double maxX, double minY, double maxY)
double BeginZoomingX (CPoint pnt, bool bDraw)
double PrepareZoomX (CPoint pnt, double startX, bool bDraw)
double BeginZoomingY (CPoint pnt, bool bDraw)
double PrepareZoomY (CPoint pnt, double startY, bool bDraw)
CH_MODE RestoreModeX (void)
CH_MODE RestoreModeY (void)
size_t PrepareDataLegend (CPoint pnt, MAP_LABSTR &mapLabels, MAP_SELPNTSD &mapSelPntsD)
size_t PrepareDataLegend (PointD origPntD, double epsX, MAP_LABSTR &mapLabels, MAP_SELPNTSD &mapSelPntsD, bool bChangeMatrix)
size_t PrepareNamesLegend (MAP_LABSTR &mapLabels)
size_t UpdateDataLegend (MAP_SELPNTSD &mapSelPntsD, MAP_LABSTR &m_mapLabs)
AX_XPOS GetXAxisPos (void) const
PAIR_XAXPOS GetXAxisPos (RectF rChartF, double minY, double maxY)
AX_YPOS GetYAxisPos (void) const
PAIR_YAXPOS GetYAxisPos (RectF rChartF, double startX, double endX)
bool ShowDataView (CChart *chartPtr, bool bClearMap, bool bRefresh=true)
bool UpdateDataView (int chartIdx, DATAVIEW_FLAGS flagsData)
size_t UpdateDataViewPntsDMap (void)
PAIR_DBLS GetLocScYDelta (CChart *chartPtr)
void MoveChartsByArrowKeysX (UINT nChar)
void ChangeLocScaleYByArrowKeys (UINT nChar)
void MoveChartsByArrowKeysY (UINT nChar)
PointF DrawAxes (RectF rClientF, double startX, double endX, double minY, double maxY, Color colAxis, Graphics *grPtr, float dpiRatio=1.0f)
void DrawBkground (RectF rClientF, Color colBkground, Color colBorder, Graphics *grPtr)
bool DrawSelPntsD (CChart *chartPtr, const MAP_SELPNTSD &mapSelPntsD, GraphicsPath *grPathPtr, Graphics *grPtr, RectF drawRF, float dpiRatio=1.0f)
bool DrawDataViewPntsD (const MAP_SELPNTSD &mapDataViewPntsD, double startX, double endX, GraphicsPath *grPathPtr, Graphics *grPtr, float dpiRatio=1.0f)
void DrawSelLine (RectF clRF, Graphics *grPtr, int selChartIdx=-1, float dpiRatio=1.0f)
void DrawAxXBoundaryStr (RectF boundRF, Graphics *grPtr, float dpiRtio=1.0f)
void DrawZoomBorderX (CPoint pnt)
void DrawZoomBorderY (CPoint pnt)
void DrawGrid (RectF boundRF, PointF coordOrigF, Graphics *grPtr, float dpiRatio=1.0f)
void DrawContainerToBmp (Rect rGdi, Bitmap &clBmp)
int GetScreenDpi (void)
TUPLE_PRNLEGLAYOUT CalcNamesPntLayout (RectF namesRF, const MAP_PRNDATA &mapPrnData, Graphics *grPtr, float dpiRatio)
void PrintCrossLine (PointF pntStartF, PointF pntEndF, SizeF sizeCrossF, Pen *penPtr, Graphics *grPtr, float dpiRatio)
void GetSelValString (RectF drawRF, CChart *chartPtr, double pageScY, MAP_PRNDATA &mapPrnData, float dpiRatio)
size_t PrintChartNames (RectF namesRF, const MAP_PRNDATA &mapPrnData, const TUPLE_PRNLEGLAYOUT &tuple_prnLayout, Graphics *grPtr, float dpiRatio, size_t mapOffs=0)
string_t PrintPageHeader (RectF rGdiF, const CChartContainer *pContainer, string_t tmStr, Graphics *grPtr)
afx_msg void OnPaint (void)
afx_msg void OnSize (UINT nType, int cx, int cy)
afx_msg UINT OnGetDlgCode ()
afx_msg void OnLButtonDown (UINT nFlags, CPoint point)
afx_msg void OnLButtonDblClk (UINT nFlags, CPoint point)
afx_msg void OnLButtonUp (UINT nFlags, CPoint point)
afx_msg void OnMButtonDown (UINT nFlags, CPoint point)
afx_msg BOOL OnMouseWheel (UINT nFlags, short zDelta, CPoint pt)
afx_msg void OnKeyDown (UINT nChar, UINT nRepCnt, UINT nFlags)
afx_msg BOOL OnSetCursor (CWnd *pWnd, UINT nHitTest, UINT message)
afx_msg void OnTimer (UINT_PTR nIDEvent)
afx_msg void OnKillFocus (CWnd *pNewWnd)
afx_msg void OnSetFocus (CWnd *pOldWnd)
afx_msg void OnContextMenu (CWnd *, CPoint)
afx_msg void OnMnShowLegend (void)
afx_msg void OnMnShowAxBoundaries (void)
afx_msg void OnMnRefresh (void)
afx_msg void OnMnViewData (void)
afx_msg void OnMnSaveCharts (void)
afx_msg void OnMnSaveImage (void)
afx_msg void OnMnPrintCharts (void)
afx_msg void OnMnZoomInX (void)
afx_msg void OnMnMoveRight (void)
afx_msg void OnMnMoveLeft (void)
afx_msg void OnMnZoomInY (void)
afx_msg void OnMnMoveUp (void)
afx_msg void OnMnMoveDown (void)
afx_msg void OnMnUndoHistStepX (void)
afx_msg void OnMnUndoHistStepY (void)
afx_msg void OnMnEnableTracking (void)
afx_msg void OnMnShowPnts (void)
afx_msg void OnMnShowChart (UINT nCmdID)
Protected Attributes
Color m_colBkground
Color m_colBorder
Color m_colAxis
Color m_colZoomBorder
Color m_colLegPnts
Color m_colDataViewPnts
Color m_colLegBkgnd
Color m_colLegBorder
Color m_colGrid
double m_minExtY
double m_maxExtY
double m_startX
double m_endX
float m_axOffsXF
AX_XPOS m_axXPos
AX_YPOS m_axYPos
double m_scX
double m_scY
bool m_bTracking
bool m_bHasNamesLeg
bool m_bUserEnabled
bool m_bAxBoundaries
int m_chartSelIdx
int m_dataViewChartIdx
int m_precision
double m_tmpZX
double m_tmpZY
MatrixD * m_pMatrixD
PointD m_dataLegPntD
double m_epsX
V_HIST m_vHistX
V_HIST m_vHistY
MAP_CHARTS m_mapCharts
MAP_SELPNTSD m_mapSelPntsD
MAP_SELPNTSD m_mapDataViewPntsD
CDataWnd * m_pDataWnd
CDataWnd * m_pLegWnd
CChartDataView * m_pChartDataView
CH_MODE m_chModeX
CH_MODE m_chModeY
string_t m_name
string_t m_labelX
val_label_str_fn m_pLabValStrFnPtr
Friends
class CDataView
Detailed Description
Definition at line 34 of file ChartContainer.h.
Constructor & Destructor Documentation
CChartContainer::CChartContainer (string_t name = string_t(_T("")))
Definition at line 25 of file ChartContainer.cpp.
CChartContainer::~CChartContainer () virtual
Definition at line 51 of file ChartContainer.cpp.
Member Function Documentation
int CChartContainer::AddChart (bool bVisible, bool bShowPnts, string_t label, string_t labelY, int precisionY, DashStyle dashStyle, float penWidth, float tension, Color colChart, V_CHARTDATAD & vData, bool bRedraw = false)
Definition at line 2024 of file ChartContainer.cpp.
References CChart::GetChartIdx(), CChart::GetMaxValX(), CChart::GetMaxValY(), CChart::GetMinValX(), CChart::GetMinValY(), CChart::m_vDataPnts, NormalizeString(), CChart::SetChartAttr(), CChart::SetMaxValX(), CChart::SetMaxValY(), CChart::SetMinValX(), CChart::SetMinValY(), STR_MAXLEN, and STR_NORMSIGN.
Referenced by CChartsXMLSerializer::ReplaceChartsFromXMLFile(), and CChartsXMLSerializer::XMLToCharts().
int CChartContainer::AddChart (bool bVisible, bool bShowPnts, string_t label, string_t labelY, int precisionY, DashStyle dashStyle, float penWidth, float tension, Color colChart, std::vector< double > & vTmSeries, double startX = 0.0, double stepX = 1.0, bool bRedraw = false)
Definition at line 2111 of file ChartContainer.cpp.
int CChartContainer::AddChart (bool bVisible, bool bShowPnts, string_t label, string_t labelY, int precisionY, DashStyle dashStyle, float penWidth, float tension, Color colChart, std::vector< std::pair< double, double > > & vXYData, bool bRedraw = false)
Definition at line 2125 of file ChartContainer.cpp.
int CChartContainer::AddChart (bool bVisible, bool bShowPnts, string_t label, string_t labelY, int precisionY, DashStyle dashStyle, float penWidth, float tension, Color colChart, std::vector< double > & vX, std::vector< double > & vY, bool bRedraw = false)
Definition at line 2138 of file ChartContainer.cpp.
bool CChartContainer::AllowChartPnts (int chartIdx, bool bAllowed, bool bVisibleOnly, bool bRedraw = false)
Definition at line 1386 of file ChartContainer.cpp.
References CChart::AllowPnts(), CChart::ArePntsAllowed(), and CChart::IsChartVisible().
bool CChartContainer::AppendChartData (int chartIdx, V_CHARTDATAD & vData, bool bUpdate = false)
Definition at line 2159 of file ChartContainer.cpp.
References CChart::AppendChartData(), F_APPEND, CChart::GetMaxValX(), CChart::GetMaxValY(), CChart::GetMinValX(), CChart::GetMinValY(), and CChart::IsChartVisible().
bool CChartContainer::AppendChartData (int chartIdx, std::vector< double > & vTmSeries, double startX = 0.0, double stepX = 1.0, bool bUpdate = false)
Definition at line 2197 of file ChartContainer.cpp.
bool CChartContainer::AppendChartData (int chartIdx, std::vector< std::pair< double, double > > & vXYData, bool bUpdate = false)
Definition at line 2210 of file ChartContainer.cpp.
bool CChartContainer::AppendChartData (int chartIdx, std::vector< double > & vX, std::vector< double > & vY, bool bUpdate = false)
Definition at line 2223 of file ChartContainer.cpp.
std::pair< bool, bool > CChartContainer::AreChartPntsAllowed (int chartIdx) const
Definition at line 1378 of file ChartContainer.cpp.
double CChartContainer::BeginZoomingX (CPoint pnt, bool bDraw) protected
Definition at line 2928 of file ChartContainer.cpp.
References MODE_ZOOMINGX, and PointT< T >::X.
double CChartContainer::BeginZoomingY (CPoint pnt, bool bDraw) protected
Definition at line 2977 of file ChartContainer.cpp.
References MODE_ZOOMINGY, and PointT< T >::Y.
TUPLE_PRNLEGLAYOUT CChartContainer::CalcNamesPntLayout (RectF namesRF, const MAP_PRNDATA & mapPrnData, Graphics * grPtr, float dpiRatio) protected
Definition at line 3945 of file ChartContainer.cpp.
References LB_BORDERSPACE, LB_BULLETSZ, STEPY_VALSTR, and STEPY_VALY.
Referenced by PrintCharts().
bool CChartContainer::ChangeChartName (int chartIdx, string_t name, bool bRedraw = false)
Definition at line 1629 of file ChartContainer.cpp.
References NormalizeString(), STR_MAXLEN, and STR_NORMSIGN.
bool CChartContainer::ChangeChartYValName (int chartIdx, string_t nameY, bool bVisibleOnly, bool bRedraw = false)
Definition at line 1663 of file ChartContainer.cpp.
References F_NODATACHANGE, NormalizeString(), STR_MAXLEN, and STR_NORMSIGN.
void CChartContainer::ChangeLocScaleYByArrowKeys (UINT nChar) protected
Definition at line 3370 of file ChartContainer.cpp.
References CODE_SCY, DELTA_LOCY, CChart::GetChartIdx(), CChart::IsChartSelected(), CChart::IsChartVisible(), and CChart::SetLocScaleY().
bool CChartContainer::ClearDataViewChartIdx (void)
Definition at line 603 of file ChartContainer.cpp.
CChart * CChartContainer::CloneChart (int chartIdx, bool bCloneState = false) protected
Definition at line 269 of file ChartContainer.cpp.
References CChart::CloneChart().
CChartContainer * CChartContainer::CloneChartContainer (string_t name = string_t(_T("")), bool bCloneState = false)
Definition at line 198 of file ChartContainer.cpp.
References CChart::CloneChart(), CChart::GetChartIdx(), m_bAxBoundaries, m_bHasNamesLeg, m_bTracking, m_bUserEnabled, m_chartSelIdx, m_chModeX, m_chModeY, m_colAxis, m_colBkground, m_colBorder, m_colDataViewPnts, m_colGrid, m_colLegBkgnd, m_colLegBorder, m_colLegPnts, m_colZoomBorder, m_dataLegPntD, m_endX, m_epsX, m_labelX, m_mapCharts, m_mapSelPntsD, m_maxExtY, m_minExtY, m_name, m_pLabValStrFnPtr, m_precision, m_startX, m_vHistX, m_vHistY, MODE_FULLX, and MODE_FULLY.
void CChartContainer::CopyDataLegendWnd (void) protected
Definition at line 2738 of file ChartContainer.cpp.
size_t CChartContainer::CopyHistory (V_HIST & vHistDst, const V_HIST & vHistSrc) const inline
Definition at line 140 of file ChartContainer.h.
bool CChartContainer::CreateChartCtrlWnd (DWORD dwExStyle, DWORD dwStyle, const CRect & wndRect, CWnd * pParent, UINT nID)
Definition at line 171 of file ChartContainer.cpp.
CChartDataView * CChartContainer::DestroyChartDataView (void)
Definition at line 2844 of file ChartContainer.cpp.
Referenced by CChartDataView::UpdateParams().
CDataWnd * CChartContainer::DestroyLabWnd (CDataWnd * pDataWnd, bool bRedraw = true)
Definition at line 2771 of file ChartContainer.cpp.
References CDataWnd::IsDataLeg().
PointF CChartContainer::DrawAxes (RectF rClientF, double startX, double endX, double minY, double maxY, Color colAxis, Graphics * grPtr, float dpiRatio = 1.0f) protected
Definition at line 3425 of file ChartContainer.cpp.
References AXIS_PENWIDTH, and DR_SPACE.
Referenced by PrintCharts().
void CChartContainer::DrawAxXBoundaryStr (RectF boundRF, Graphics * grPtr, float dpiRtio = 1.0f) protected
Definition at line 3613 of file ChartContainer.cpp.
References BETWEEN, BOTTOM, DR_SPACE, LEFT, MIDDLE, RIGHT, and TOP.
Referenced by PrintCharts().
void CChartContainer::DrawBkground (RectF rClientF, Color colBkground, Color colBorder, Graphics * grPtr) protected
Definition at line 3456 of file ChartContainer.cpp.
void CChartContainer::DrawContainerToBmp (Rect rGdi, Bitmap & clBmp) protected
Definition at line 3850 of file ChartContainer.cpp.
References BETWEEN, BOTTOM, MatrixD::Clone(), DR_SPACE, CChart::DrawChartCurve(), GdiRectToRectF(), CChart::IsChartVisible(), LEFT, CChart::m_vDataPnts, MIDDLE, RIGHT, MatrixD::Scale(), TOP, and MatrixD::Translate().
bool CChartContainer::DrawDataViewPntsD (const MAP_SELPNTSD & mapDataViewPntsD, double startX, double endX, GraphicsPath * grPathPtr, Graphics * grPtr, float dpiRatio = 1.0f) protected
Definition at line 3527 of file ChartContainer.cpp.
References CHART_DTPNTSZ, CChart::ConvertChartData(), CChart::IsChartVisible(), and RectFFromCenterF().
void CChartContainer::DrawGrid (RectF boundRF, PointF coordOrigF, Graphics * grPtr, float dpiRatio = 1.0f) protected
Definition at line 3805 of file ChartContainer.cpp.
Referenced by PrintCharts().
void CChartContainer::DrawSelLine (RectF clRF, Graphics * grPtr, int selChartIdx = -1, float dpiRatio = 1.0f) protected
Definition at line 3567 of file ChartContainer.cpp.
References DR_SPACE, and CChart::GetLocScaleY().
Referenced by PrintCharts().
bool CChartContainer::DrawSelPntsD (CChart * chartPtr, const MAP_SELPNTSD & mapSelPntsD, GraphicsPath * grPathPtr, Graphics * grPtr, RectF drawRF, float dpiRatio = 1.0f) protected
Definition at line 3473 of file ChartContainer.cpp.
References CHART_DTPNTSZ, DR_SPACE, CChart::GetChartIdx(), CChart::GetLocScaleY(), in_range(), RectFFromCenterF(), and PointT< T >::X.
Referenced by PrintCharts().
void CChartContainer::DrawZoomBorderX (CPoint pnt) protected
Definition at line 3685 of file ChartContainer.cpp.
void CChartContainer::DrawZoomBorderY (CPoint pnt) protected
Definition at line 3744 of file ChartContainer.cpp.
void CChartContainer::EnableUser (bool bEnable, bool bClearState = true)
Definition at line 401 of file ChartContainer.cpp.
void CChartContainer::EqualizeVertRanges (double spaceMult, bool bRedraw = false)
Definition at line 5397 of file ChartContainer.cpp.
References BOTTOM, CChart::GetMaxValY(), CChart::GetMinValY(), MIDDLE, and TOP.
bool CChartContainer::ExportChartData (string_t chartName, V_CHARTDATAD & vDataPnts) const
Definition at line 1129 of file ChartContainer.cpp.
References CChart::m_vDataPnts.
bool CChartContainer::ExportChartData (string_t chartName, std::vector< std::pair< double, double > > & vPairs) const
Definition at line 1147 of file ChartContainer.cpp.
References CChart::m_vDataPnts, PointT< T >::X, and PointT< T >::Y.
bool CChartContainer::ExportChartData (string_t chartName, std::vector< double > & vX, std::vector< double > & vY) const
Definition at line 1170 of file ChartContainer.cpp.
References CChart::m_vDataPnts, PointT< T >::X, and PointT< T >::Y.
MAP_CHARTS::iterator CChartContainer::FindChart (int chartIdx) inline
Definition at line 136 of file ChartContainer.h.
Referenced by CChartsXMLSerializer::ChartDataToXML().
MAP_CHARTS::const_iterator CChartContainer::FindChart (int chartIdx) const inline
Definition at line 137 of file ChartContainer.h.
CChart * CChartContainer::FindChartByName (string_t nameStr) const protected
Definition at line 1762 of file ChartContainer.cpp.
Color CChartContainer::GetAxesColor (void) const inline
Definition at line 60 of file ChartContainer.h.
Referenced by ResetChartContainer().
float CChartContainer::GetAxisOffsetX (void) const inline
Definition at line 387 of file ChartContainer.h.
Referenced by ResetChartContainer().
string_t CChartContainer::GetAxisXName (void) const inline
Definition at line 120 of file ChartContainer.h.
Referenced by CChartsXMLSerializer::ChartDataToXML(), CChartDataView::InitParams(), and CChartDataView::UpdateParams().
Color CChartContainer::GetBkColor (void) const inline
Definition at line 58 of file ChartContainer.h.
Referenced by ResetChartContainer().
Color CChartContainer::GetBorderColor (void) const inline
Definition at line 59 of file ChartContainer.h.
Referenced by ResetChartContainer().
CChart * CChartContainer::GetChart (int chartIdx, bool bVisibleOnly = false) const protected
Definition at line 1736 of file ChartContainer.cpp.
References CChart::IsChartVisible().
std::tuple< double, double, bool > CChartContainer::GetChartBoundaries (int chartIdx, bool bY = false) const
Returns false in the third member of the tuple if the chart does not exist
Definition at line 1202 of file ChartContainer.cpp.
std::pair< Color, bool > CChartContainer::GetChartColor (int chartIdx) const
Definition at line 1414 of file ChartContainer.cpp.
std::pair< DashStyle, bool > CChartContainer::GetChartDashStyle (int chartIdx) const
Definition at line 1448 of file ChartContainer.cpp.
V_CHARTDATAD * CChartContainer::GetChartData (int chartIdx)
Definition at line 1754 of file ChartContainer.cpp.
References CChart::m_vDataPnts.
int CChartContainer::GetChartIdx (string_t chartName) const
Definition at line 1778 of file ChartContainer.cpp.
References CChart::GetChartIdx().
Referenced by CChartsXMLSerializer::ChartDataToXML().
std::pair< double, bool > CChartContainer::GetChartLocScaleY (int chartIdx) const
Definition at line 1786 of file ChartContainer.cpp.
string_t CChartContainer::GetChartName (int chartIdx) const
Definition at line 1621 of file ChartContainer.cpp.
Referenced by SaveChartData().
HRESULT CChartContainer::GetChartNamesFromXMLFile (LPCTSTR fileName, MAP_CHARTCOLS & mapContent)
Definition at line 1119 of file ChartContainer.cpp.
References CChartsXMLSerializer::GetChartNamesFromXMLFile().
HRESULT CChartContainer::GetChartNamesFromXMLFile (LPCTSTR fileName, MAP_NAMES & mapNames)
Definition at line 1124 of file ChartContainer.cpp.
References CChartsXMLSerializer::GetChartNamesFromXMLFile().
std::pair< float, bool > CChartContainer::GetChartPenWidth (int chartIdx) const
Definition at line 1308 of file ChartContainer.cpp.
int CChartContainer::GetChartPrecisionY (int chartIdx) const
Definition at line 1582 of file ChartContainer.cpp.
MAP_CHARTS::iterator CChartContainer::GetChartsEnd (void) inline
Definition at line 134 of file ChartContainer.h.
Referenced by CChartsXMLSerializer::ChartDataToXML().
MAP_CHARTS::const_iterator CChartContainer::GetChartsEnd (void) const inline
Definition at line 135 of file ChartContainer.h.
std::pair< float, bool > CChartContainer::GetChartTension (int chartIdx) const
Definition at line 1343 of file ChartContainer.cpp.
string_t CChartContainer::GetChartYValName (int chartIdx) const
Definition at line 1655 of file ChartContainer.cpp.
CH_MODE CChartContainer::GetChModeX (void) const inline protected
Definition at line 147 of file ChartContainer.h.
Referenced by ResetChartContainer().
CH_MODE CChartContainer::GetChModeY (void) const inline protected
Definition at line 148 of file ChartContainer.h.
Referenced by ResetChartContainer().
V_HIST& CChartContainer::GetContainerHistory (bool bY = false) inline
Definition at line 139 of file ChartContainer.h.
string_t CChartContainer::GetContainerName (void) const inline
Definition at line 117 of file ChartContainer.h.
Referenced by CChartsXMLSerializer::ChartDataToXML().
int CChartContainer::GetContainerPrecisionX (void) const inline
Definition at line 107 of file ChartContainer.h.
Referenced by CChartsXMLSerializer::ChartDataToXML(), CChartDataView::InitParams(), and CChartDataView::UpdateParams().
size_t CChartContainer::GetContainerSize (void) const inline
Definition at line 130 of file ChartContainer.h.
PointD CChartContainer::GetDataLegPntD (void) const inline
Definition at line 326 of file ChartContainer.h.
Referenced by ResetChartContainer().
int CChartContainer::GetDataViewChartIdx (void) const inline
Definition at line 110 of file ChartContainer.h.
Color CChartContainer::GetDataViewPntsColor (void) const inline
Definition at line 63 of file ChartContainer.h.
Referenced by ResetChartContainer().
const MAP_SELPNTSD* CChartContainer::GetDataViewSelPntsD (void) const inline
Definition at line 112 of file ChartContainer.h.
double CChartContainer::GetEndX (void) const inline
Definition at line 80 of file ChartContainer.h.
Referenced by ResetChartContainer().
MAP_CHARTS::iterator CChartContainer::GetFirstChart (void) inline
Definition at line 132 of file ChartContainer.h.
Referenced by CChartsXMLSerializer::ChartDataToXML().
MAP_CHARTS::const_iterator CChartContainer::GetFirstChart (void) const inline
Definition at line 133 of file ChartContainer.h.
Color CChartContainer::GetGridColor (void) const inline
Definition at line 66 of file ChartContainer.h.
Referenced by ResetChartContainer().
double CChartContainer::GetInitialEndX (void) const
Definition at line 386 of file ChartContainer.cpp.
double CChartContainer::GetInitialMaxExtY (void) const
Definition at line 396 of file ChartContainer.cpp.
double CChartContainer::GetInitialMinExtY (void) const
Definition at line 391 of file ChartContainer.cpp.
double CChartContainer::GetInitialStartX (void) const
Definition at line 381 of file ChartContainer.cpp.
val_label_str_fn CChartContainer::GetLabXValStrFnPtr (void) const inline
Definition at line 123 of file ChartContainer.h.
Referenced by CChartsXMLSerializer::ChartDataToXML(), CChartDataView::InitParams(), and CChartDataView::UpdateParams().
val_label_str_fn CChartContainer::GetLabYValStrFnPtr (int chartIdx) const
Definition at line 1696 of file ChartContainer.cpp.
Color CChartContainer::GetLegBkgndColor (void) const inline
Definition at line 64 of file ChartContainer.h.
Referenced by ResetChartContainer().
Color CChartContainer::GetLegBorderColor (void) const inline
Definition at line 65 of file ChartContainer.h.
Referenced by ResetChartContainer().
Color CChartContainer::GetLegPntsColor (void) const inline
Definition at line 62 of file ChartContainer.h.
Referenced by ResetChartContainer().
PAIR_DBLS CChartContainer::GetLocScYDelta (CChart * chartPtr) protected
Definition at line 3341 of file ChartContainer.cpp.
References CChart::GetLocScaleY(), CChart::GetMaxValY(), and CChart::GetMinValY().
MAP_CHARTS* CChartContainer::GetMapCharts (void) inline
Definition at line 131 of file ChartContainer.h.
Referenced by CChartsXMLSerializer::XMLToCharts().
int CChartContainer::GetMaxChartIdx (void) const
Definition at line 2862 of file ChartContainer.cpp.
double CChartContainer::GetMaxY (void) const inline
Definition at line 87 of file ChartContainer.h.
Referenced by ResetChartContainer().
PAIR_DBLS CChartContainer::GetMinMaxExtX (void) const
Definition at line 785 of file ChartContainer.cpp.
References CChart::GetMaxValX(), and CChart::GetMinValX().
PAIR_DBLS CChartContainer::GetMinMaxExtY (void) const
Definition at line 809 of file ChartContainer.cpp.
References CChart::GetMaxValY(), and CChart::GetMinValY().
double CChartContainer::GetMinY (void) const inline
Definition at line 86 of file ChartContainer.h.
Referenced by ResetChartContainer().
int CChartContainer::GetScreenDpi (void) protected
Definition at line 3936 of file ChartContainer.cpp.
double CChartContainer::GetScX (void) const inline
Definition at line 89 of file ChartContainer.h.
Referenced by ResetChartContainer().
double CChartContainer::GetScY (void) const inline
Definition at line 90 of file ChartContainer.h.
Referenced by ResetChartContainer().
void CChartContainer::GetSelValString (RectF drawRF, CChart * chartPtr, double pageScY, MAP_PRNDATA & mapPrnData, float dpiRatio) protected
Definition at line 4124 of file ChartContainer.cpp.
References DR_SPACE, CChart::GetAxisYName(), CChart::GetChartColor(), CChart::GetChartDashStyle(), CChart::GetChartIdx(), CChart::GetChartName(), CChart::GetLabYValStrFnPtr(), CChart::GetLocScaleY(), CChart::GetMaxValY(), CChart::GetMinValY(), CChart::GetPenWidth(), CChart::GetPrecisionY(), and SetAlpha().
Referenced by PrintCharts().
double CChartContainer::GetStartX (void) const inline
Definition at line 79 of file ChartContainer.h.
Referenced by ResetChartContainer().
MatrixD* CChartContainer::GetTransformMatrixD (void) const inline
Definition at line 144 of file ChartContainer.h.
MatrixD * CChartContainer::GetTransformMatrixD (double startX, double endX, double minY, double maxY) protected
Definition at line 732 of file ChartContainer.cpp.
References BETWEEN, BOTTOM, MatrixD::Clone(), DR_SPACE, LEFT, MIDDLE, RIGHT, MatrixD::Scale(), TOP, and MatrixD::Translate().
CChart * CChartContainer::GetVisibleChart (int chartIdx) const protected
Definition at line 1211 of file ChartContainer.cpp.
References CChart::HasData(), and CChart::IsChartVisible().
AX_XPOS CChartContainer::GetXAxisPos (void) const inline protected
Definition at line 381 of file ChartContainer.h.
Referenced by ResetChartContainer().
PAIR_XAXPOS CChartContainer::GetXAxisPos (RectF rChartF, double minY, double maxY) protected
Definition at line 3176 of file ChartContainer.cpp.
References BOTTOM, MIDDLE, and TOP.
AX_YPOS CChartContainer::GetYAxisPos (void) const inline protected
Definition at line 384 of file ChartContainer.h.
Referenced by ResetChartContainer().
PAIR_YAXPOS CChartContainer::GetYAxisPos (RectF rChartF, double startX, double endX) protected
Definition at line 3203 of file ChartContainer.cpp.
References BETWEEN, LEFT, and RIGHT.
Color CChartContainer::GetZoomBorderColor (void) const inline
Definition at line 61 of file ChartContainer.h.
Referenced by ResetChartContainer().
int CChartContainer::HasChartDifferentPnts (int chartIdx, bool bVisibleOnly = false) const
Definition at line 669 of file ChartContainer.cpp.
References CChart::GetChartIdx(), CChart::GetMaxValX(), CChart::GetMaxValY(), CChart::GetMinValX(), CChart::GetMinValY(), and CChart::IsChartVisible().
bool CChartContainer::HasChartWithData (int chartIdx, bool bVisibleOnly = false) const
Definition at line 649 of file ChartContainer.cpp.
bool CChartContainer::HasNamesLeg (void) const inline
Definition at line 96 of file ChartContainer.h.
int CChartContainer::HasSelectedChart (void) const
Definition at line 1488 of file ChartContainer.cpp.
Referenced by PrintCharts().
bool CChartContainer::HasVisiblePntsDInYBand (int chartIdx, double minY, double maxY)
Definition at line 691 of file ChartContainer.cpp.
References CChart::GetLocScaleY(), CChart::GetStartEndDataIterators(), in_range(), CChart::IsChartVisible(), CChart::m_vDataPnts, and PointT< T >::Y.
bool CChartContainer::HideLabWnds (bool bRedraw = false)
Definition at line 2826 of file ChartContainer.cpp.
bool CChartContainer::IsChartVisible (int chartIdx) const
Definition at line 1226 of file ChartContainer.cpp.
Referenced by CChartsXMLSerializer::ChartDataToXML().
bool CChartContainer::IsContainerEmpty (void) const inline
Definition at line 126 of file ChartContainer.h.
Referenced by CChartsXMLSerializer::ChartDataToXML().
bool CChartContainer::IsLabWndExist (bool bLeg) const
Definition at line 2762 of file ChartContainer.cpp.
Referenced by operator=().
bool CChartContainer::IsLabWndVisible (bool bLeg) const
Definition at line 2753 of file ChartContainer.cpp.
bool CChartContainer::IsUserEnabled (void) const inline
Definition at line 93 of file ChartContainer.h.
HRESULT CChartContainer::LoadCharts (LPCTSTR fileName, const MAP_CHARTCOLS & mapContent, bool bClearCharts = false)
Definition at line 1094 of file ChartContainer.cpp.
References CChartsXMLSerializer::XMLToCharts().
void CChartContainer::MousePntToPntD (CPoint pnt, PointD & dataPntD, MatrixD * pMatrixD, double locScY = 1.0) protected
Definition at line 2874 of file ChartContainer.cpp.
References MatrixD::TransformToPntD(), PointT< T >::X, and PointT< T >::Y.
Referenced by PrintCharts().
void CChartContainer::MoveChartsByArrowKeysX (UINT nChar) protected
Definition at line 3356 of file ChartContainer.cpp.
References MOVE_DELTAX.
void CChartContainer::MoveChartsByArrowKeysY (UINT nChar) protected
Definition at line 3407 of file ChartContainer.cpp.
References CODE_EXTY, and MOVE_DELTAY.
CH_MODE CChartContainer::MoveContainerChartsX (double deltaX, bool bRedraw = false) protected
Definition at line 1878 of file ChartContainer.cpp.
References MODE_FULLX, MODE_ZOOMEDX, and MODE_ZOOMX.
CH_MODE CChartContainer::MoveContainerChartsY (double deltaY, bool bRedraw = false) protected
Definition at line 1959 of file ChartContainer.cpp.
References MODE_MOVEDY, MODE_MOVEY, and MODE_ZOOMEDY.
void CChartContainer::OnChangedSize (int cx, int cy)
Definition at line 905 of file ChartContainer.cpp.
void CChartContainer::OnContextMenu (CWnd * , CPoint point) protected
Definition at line 4858 of file ChartContainer.cpp.
References CChart::ArePntsAllowed(), IDM_CHART_FIRSTCHART, and IDM_CHART_TEST.
UINT CChartContainer::OnGetDlgCode () protected
Definition at line 4658 of file ChartContainer.cpp.
void CChartContainer::OnKeyDown (UINT nChar, UINT nRepCnt, UINT nFlags) protected
Definition at line 4787 of file ChartContainer.cpp.
References MODE_ZOOMINGX, and MODE_ZOOMINGY.
void CChartContainer::OnKillFocus (CWnd * pNewWnd) protected
Definition at line 4845 of file ChartContainer.cpp.
void CChartContainer::OnLButtonDblClk (UINT nFlags, CPoint point) protected
Definition at line 4691 of file ChartContainer.cpp.
References MODE_ZOOMINGY, and MODE_ZOOMY.
void CChartContainer::OnLButtonDown (UINT nFlags, CPoint point) protected
Definition at line 4665 of file ChartContainer.cpp.
References MODE_ZOOMINGX, MODE_ZOOMINGY, and MODE_ZOOMX.
void CChartContainer::OnLButtonUp (UINT nFlags, CPoint point) protected
Definition at line 4704 of file ChartContainer.cpp.
References MODE_FULLX, MODE_FULLY, MODE_ZOOMEDX, MODE_ZOOMEDY, MODE_ZOOMX, and MODE_ZOOMY.
void CChartContainer::OnMButtonDown (UINT nFlags, CPoint point) protected
Definition at line 4720 of file ChartContainer.cpp.
void CChartContainer::OnMnEnableTracking (void) protected
Definition at line 5217 of file ChartContainer.cpp.
References CODE_TRACKING.
void CChartContainer::OnMnMoveDown (void) protected
Definition at line 5198 of file ChartContainer.cpp.
References CODE_EXTY, and MOVE_DELTAY.
void CChartContainer::OnMnMoveLeft (void) protected
Definition at line 5131 of file ChartContainer.cpp.
References CODE_EXTX, and MOVE_DELTAX.
void CChartContainer::OnMnMoveRight (void) protected
Definition at line 5123 of file ChartContainer.cpp.
References CODE_EXTX, and MOVE_DELTAX.
void CChartContainer::OnMnMoveUp (void) protected
Definition at line 5190 of file ChartContainer.cpp.
References CODE_EXTY, and MOVE_DELTAY.
void CChartContainer::OnMnPrintCharts (void) protected
Definition at line 5059 of file ChartContainer.cpp.
References CODE_PRINTED, and CODE_PRINTING.
void CChartContainer::OnMnRefresh (void) protected
Definition at line 4998 of file ChartContainer.cpp.
References CODE_REFRESH.
void CChartContainer::OnMnSaveCharts (void) protected
Definition at line 5032 of file ChartContainer.cpp.
void CChartContainer::OnMnSaveImage (void) protected
Definition at line 5042 of file ChartContainer.cpp.
void CChartContainer::OnMnShowAxBoundaries (void) protected
Definition at line 4992 of file ChartContainer.cpp.
void CChartContainer::OnMnShowChart (UINT nCmdID) protected
Definition at line 5257 of file ChartContainer.cpp.
References CODE_VISIBILITY, and IDM_CHART_FIRSTCHART.
void CChartContainer::OnMnShowLegend (void) protected
Definition at line 4984 of file ChartContainer.cpp.
void CChartContainer::OnMnShowPnts (void) protected
Definition at line 5228 of file ChartContainer.cpp.
References CChart::AllowPnts(), CChart::ArePntsAllowed(), and CODE_SHOWPNTS.
void CChartContainer::OnMnUndoHistStepX (void) protected
Definition at line 5205 of file ChartContainer.cpp.
References CODE_EXTX.
void CChartContainer::OnMnUndoHistStepY (void) protected
Definition at line 5211 of file ChartContainer.cpp.
References CODE_EXTY.
void CChartContainer::OnMnViewData (void) protected
Definition at line 5004 of file ChartContainer.cpp.
void CChartContainer::OnMnZoomInX (void) protected
Definition at line 5085 of file ChartContainer.cpp.
References CODE_EXTX, and MODE_ZOOMINGX.
void CChartContainer::OnMnZoomInY (void) protected
Definition at line 5139 of file ChartContainer.cpp.
References CODE_EXTY, MODE_FULLY, and MODE_ZOOMINGY.
BOOL CChartContainer::OnMouseWheel (UINT nFlags, short zDelta, CPoint pt) protected
Definition at line 4738 of file ChartContainer.cpp.
References DELTA_LOCY, CChart::IsChartSelected(), CChart::IsChartVisible(), MOVE_DELTAX, and CChart::SetLocScaleY().
void CChartContainer::OnPaint (void) protected
Definition at line 4562 of file ChartContainer.cpp.
References BETWEEN, BOTTOM, MatrixD::Clone(), DR_SPACE, CChart::DrawChartCurve(), GdiRectToRectF(), CChart::IsChartVisible(), LEFT, CChart::m_vDataPnts, MIDDLE, RIGHT, MatrixD::Scale(), TOP, and MatrixD::Translate().
BOOL CChartContainer::OnSetCursor (CWnd * pWnd, UINT nHitTest, UINT message) protected
Definition at line 4810 of file ChartContainer.cpp.
void CChartContainer::OnSetFocus (CWnd * pOldWnd) protected
Definition at line 4851 of file ChartContainer.cpp.
void CChartContainer::OnSize (UINT nType, int cx, int cy) protected
Definition at line 4644 of file ChartContainer.cpp.
void CChartContainer::OnTimer (UINT_PTR nIDEvent) protected
Definition at line 4829 of file ChartContainer.cpp.
CChartContainer & CChartContainer::operator= (const CChartContainer & rhs)
Definition at line 83 of file ChartContainer.cpp.
References BETWEEN, CChart::CloneChart(), IsLabWndExist(), m_bAxBoundaries, m_bHasNamesLeg, m_bTracking, m_bUserEnabled, m_chartSelIdx, m_chModeX, m_chModeY, m_colAxis, m_colBkground, m_colBorder, m_colDataViewPnts, m_colGrid, m_colLegBkgnd, m_colLegBorder, m_colLegPnts, m_colZoomBorder, m_dataLegPntD, m_endX, m_epsX, m_labelX, m_mapCharts, m_mapSelPntsD, m_maxExtY, m_minExtY, m_name, m_pLabValStrFnPtr, m_precision, m_startX, m_vHistX, m_vHistY, and MIDDLE.
size_t CChartContainer::PrepareDataLegend (CPoint pnt, MAP_LABSTR & mapLabels, MAP_SELPNTSD & mapSelPntsD) protected
Definition at line 3026 of file ChartContainer.cpp.
References CHART_DTPNTSZ.
size_t CChartContainer::PrepareDataLegend (PointD origPntD, double epsX, MAP_LABSTR & mapLabels, MAP_SELPNTSD & mapSelPntsD, bool bChangeMatrix) protected
Definition at line 3046 of file ChartContainer.cpp.
References CChart::GetChartIdx(), CChart::GetLocScaleY(), CChart::GetNearestPointD(), CChart::GetSelValString(), in_range(), CChart::IsChartVisible(), PointT< T >::X, and PointT< T >::Y.
size_t CChartContainer::PrepareNamesLegend (MAP_LABSTR & mapLabels) protected
Definition at line 3105 of file ChartContainer.cpp.
double CChartContainer::PrepareZoomX (CPoint pnt, double startX, bool bDraw) protected
Definition at line 2942 of file ChartContainer.cpp.
References DR_SPACE, and PointT< T >::X.
double CChartContainer::PrepareZoomY (CPoint pnt, double startY, bool bDraw) protected
Definition at line 2992 of file ChartContainer.cpp.
References DR_SPACE, and PointT< T >::Y.
size_t CChartContainer::PrintChartNames (RectF namesRF, const MAP_PRNDATA & mapPrnData, const TUPLE_PRNLEGLAYOUT & tuple_prnLayout, Graphics * grPtr, float dpiRatio, size_t mapOffs = 0) protected
Definition at line 4203 of file ChartContainer.cpp.
References CHART_DTPNTSZ, LB_BULLETSZ, STEPY_VALSTR, and STEPY_VALY.
Referenced by PrintCharts().
void CChartContainer::PrintCharts (CChartContainer * pContainer, int scrDpiX, HDC printDC) static
Definition at line 4365 of file ChartContainer.cpp.
References BETWEEN, BOTTOM, CalcNamesPntLayout(), MatrixD::Clone(), DR_SPACE, DrawAxes(), DrawAxXBoundaryStr(), CChart::DrawChartCurve(), DrawGrid(), DrawSelLine(), DrawSelPntsD(), GetSelValString(), HasSelectedChart(), CChart::IsChartVisible(), LEFT, m_axXPos, m_axYPos, m_bAxBoundaries, m_bTracking, m_colAxis, m_colBkground, m_endX, m_mapCharts, m_mapSelPntsD, m_maxExtY, m_minExtY, m_name, m_pMatrixD, m_scX, m_scY, m_startX, CChart::m_vDataPnts, MIDDLE, MousePntToPntD(), PrintChartNames(), PrintPageHeader(), RIGHT, MatrixD::Scale(), TOP, MatrixD::Translate(), and UpdateScales().
void CChartContainer::PrintCrossLine (PointF pntStartF, PointF pntEndF, SizeF sizeCrossF, Pen * penPtr, Graphics * grPtr, float dpiRatio) protected
Definition at line 4100 of file ChartContainer.cpp.
string_t CChartContainer::PrintPageHeader (RectF rGdiF, const CChartContainer * pContainer, string_t tmStr, Graphics * grPtr) protected
Definition at line 4329 of file ChartContainer.cpp.
References m_name.
Referenced by PrintCharts().
void CChartContainer::RefreshWnd (void)
Definition at line 913 of file ChartContainer.cpp.
bool CChartContainer::RemoveChart (int chartIdx, bool bCorrectMinMax, bool bRedraw)
Definition at line 2538 of file ChartContainer.cpp.
bool CChartContainer::ReplaceChartData (int chartIdx, V_CHARTDATAD & vData, bool bClip = false, bool bUpdate = false, bool bVerbose = false, bool bRedraw = false)
Definition at line 2240 of file ChartContainer.cpp.
References F_REPLACE, find_border_pnts(), CChart::m_vDataPnts, CChart::SetLocScaleY(), CChart::SetMaxValX(), CChart::SetMaxValY(), CChart::SetMinValX(), and CChart::SetMinValY().
bool CChartContainer::ReplaceChartData (int chartIdx, std::vector< double > & vTmSeries, double startX = 0.0, double stepX = 1.0, bool bClip = false, bool bUpdate = false, bool bVerbose = false, bool bRedraw = false)
Definition at line 2334 of file ChartContainer.cpp.
bool CChartContainer::ReplaceChartData (int chartIdx, std::vector< std::pair< double, double > > & vXYData, bool bClip = false, bool bUpdate = false, bool bVerbose = false, bool bRedraw = false)
Definition at line 2346 of file ChartContainer.cpp.
bool CChartContainer::ReplaceChartData (int chartIdx, std::vector< double > & vX, std::vector< double > & vY, bool bClip = false, bool bUpdate = false, bool bVerbose = false, bool bRedraw = false)
Definition at line 2357 of file ChartContainer.cpp.
HRESULT CChartContainer::ReplaceContainerCharts (LPCTSTR fileName)
Definition at line 1107 of file ChartContainer.cpp.
References CChartsXMLSerializer::ReplaceChartsFromXMLFile().
void CChartContainer::ResetChartContainer (bool bKeepCharts = false, bool bResetCols = false)
Definition at line 2403 of file ChartContainer.cpp.
References GetAxesColor(), GetAxisOffsetX(), GetBkColor(), GetBorderColor(), GetChModeX(), GetChModeY(), GetDataLegPntD(), GetDataViewPntsColor(), GetEndX(), GetGridColor(), GetLegBkgndColor(), GetLegBorderColor(), GetLegPntsColor(), GetMaxY(), GetMinY(), GetScX(), GetScY(), GetStartX(), GetXAxisPos(), GetYAxisPos(), and GetZoomBorderColor().
Referenced by CChartsXMLSerializer::ReplaceChartsFromXMLFile().
void CChartContainer::ResetCharts (bool bResetLocY = false)
Definition at line 2375 of file ChartContainer.cpp.
References CChart::IsChartVisible(), MODE_FULLX, MODE_FULLY, CChart::SetLocScaleY(), and CChart::ToggleChartVisibility().
CH_MODE CChartContainer::RestoreModeX (void) protected
Definition at line 2964 of file ChartContainer.cpp.
References MODE_FULLX, MODE_ZOOMEDX, and MODE_ZOOMINGX.
CH_MODE CChartContainer::RestoreModeY (void) protected
Definition at line 3013 of file ChartContainer.cpp.
References MODE_FULLY, MODE_ZOOMEDY, and MODE_ZOOMINGY.
HRESULT CChartContainer::SaveChartData (string_t pathName, bool bAll = false)
Definition at line 1038 of file ChartContainer.cpp.
References CChartsXMLSerializer::ChartDataToXML(), CODE_SAVECHARTS, CODE_SAVEDCHARTS, and GetChartName().
Status CChartContainer::SaveContainerImage (string_t pathName = string_t(_T("")))
Definition at line 938 of file ChartContainer.cpp.
References CODE_SAVEDIMAGE, CODE_SAVEIMAGE, and CRectToGdiRect().
int CChartContainer::SelectChart (int chartIdx, bool bRedraw = false)
Definition at line 1500 of file ChartContainer.cpp.
References CChart::GetChartIdx(), and CChart::SelectChart().
int CChartContainer::SelectChartByMouseClick (CPoint pnt, bool bRedtaw = false)
Definition at line 1535 of file ChartContainer.cpp.
References CHART_DTPNTSZ, CHART_PNTSTRSH, CChart::ConvertChartData(), CChart::GetChartIdx(), CChart::HasData(), CChart::IsChartVisible(), CChart::m_vDataPnts, and PointT< T >::X.
LRESULT CChartContainer::SendNotification (UINT code, int chartIdx = -1) protected
Definition at line 1981 of file ChartContainer.cpp.
References tagNMCHART::bState, tagNMCHART::chartIdx, CODE_EXTX, CODE_EXTY, CODE_PRINTED, CODE_PRINTING, CODE_REFRESH, CODE_SAVECHARTS, CODE_SAVEDCHARTS, CODE_SAVEDIMAGE, CODE_SAVEIMAGE, CODE_SCY, CODE_SHOWPNTS, CODE_TRACKING, CODE_VISIBILITY, tagNMCHART::hdr, tagNMCHART::maxX, tagNMCHART::maxY, tagNMCHART::minX, and tagNMCHART::minY.
void CChartContainer::SetAxesColor (Color col, bool bRedraw = false)
Definition at line 294 of file ChartContainer.cpp.
void CChartContainer::SetAxisXName (string_t nameX, bool bRedraw = false)
Definition at line 619 of file ChartContainer.cpp.
References F_NODATACHANGE, NormalizeString(), STR_MAXLEN, and STR_NORMSIGN.
Referenced by CChartsXMLSerializer::ReplaceChartsFromXMLFile(), and CChartsXMLSerializer::XMLToCharts().
void CChartContainer::SetBkColor (Color col, bool bRedraw = false)
Definition at line 280 of file ChartContainer.cpp.
void CChartContainer::SetBorderColor (Color col, bool bRedraw = false)
Definition at line 287 of file ChartContainer.cpp.
bool CChartContainer::SetChartColor (int chartIdx, Color col, bool bVisibleOnly, bool bRedraw = false)
Definition at line 1426 of file ChartContainer.cpp.
References CChart::GetChartColor(), CChart::IsChartVisible(), and CChart::SetChartColor().
bool CChartContainer::SetChartDashStyle (int chartIdx, DashStyle dashStyle, bool bVisibleOnly, bool bRedraw = false)
Definition at line 1460 of file ChartContainer.cpp.
References CChart::GetChartDashStyle(), CChart::IsChartVisible(), and CChart::SetDashStyle().
bool CChartContainer::SetChartPrecisionY (int chartIdx, int precisionY, bool bVisibleOnly, bool bRedraw = false)
Definition at line 1590 of file ChartContainer.cpp.
References F_NODATACHANGE.
bool CChartContainer::SetChartTension (int chartIdx, float tension, bool bVisibleOnly, bool bRedraw = false)
Definition at line 1351 of file ChartContainer.cpp.
References in_range().
bool CChartContainer::SetChartVisibility (int chartIdx, bool bVisible, bool bRedraw = false)
Definition at line 1231 of file ChartContainer.cpp.
void CChartContainer::SetContainerName (string_t name) inline
Definition at line 118 of file ChartContainer.h.
Referenced by CChartsXMLSerializer::ReplaceChartsFromXMLFile().
void CChartContainer::SetContainerPrecision (int precision, bool bRedraw = false)
Definition at line 562 of file ChartContainer.cpp.
References F_NODATACHANGE.
Referenced by CChartsXMLSerializer::ReplaceChartsFromXMLFile(), and CChartsXMLSerializer::XMLToCharts().
void CChartContainer::SetDataViewChartIdx (int chartIdx) inline
Definition at line 111 of file ChartContainer.h.
void CChartContainer::SetDataViewPntsColor (Color col, bool bRedraw = false)
Definition at line 331 of file ChartContainer.cpp.
size_t CChartContainer::SetDataViewSelPnts (int chartIdx, const MAP_SELPNTSD & mapSelPntsD, V_CHARTDATAD * pChartData = NULL)
Definition at line 576 of file ChartContainer.cpp.
PAIR_DBLS CChartContainer::SetExtX (bool bRedraw = false)
Definition at line 505 of file ChartContainer.cpp.
PAIR_DBLS CChartContainer::SetExtY (bool bRedraw = false)
Definition at line 531 of file ChartContainer.cpp.
void CChartContainer::SetGridColor (Color col, bool bRedraw = false)
Definition at line 374 of file ChartContainer.cpp.
void CChartContainer::SetLabXValStrFn (val_label_str_fn pLabValStrFn, bool bRedraw = false)
Definition at line 634 of file ChartContainer.cpp.
References F_NODATACHANGE.
bool CChartContainer::SetLabYValStrFn (int chartIdx, val_label_str_fn m_pLabYValStrFn, bool bVisibleOnly, bool bRedraw = false)
Definition at line 1704 of file ChartContainer.cpp.
References F_NODATACHANGE.
void CChartContainer::SetLegBkgndColor (Color col, bool bRedraw = false)
Definition at line 338 of file ChartContainer.cpp.
void CChartContainer::SetLegBorderColor (Color col, bool bRedraw = false)
Definition at line 356 of file ChartContainer.cpp.
void CChartContainer::SetLegPntsColor (Color col, bool bRedraw = false)
Definition at line 324 of file ChartContainer.cpp.
void CChartContainer::SetNamesLegFlag (bool bHasNamesLeg) inline
Definition at line 97 of file ChartContainer.h.
void CChartContainer::SetTransformMatrixD (MatrixD * pMatrixD) protected
Definition at line 770 of file ChartContainer.cpp.
References MatrixD::Clone().
void CChartContainer::SetTransformMatrixD (void) protected
Definition at line 777 of file ChartContainer.cpp.
void CChartContainer::SetZoomBorderColor (Color col)
Definition at line 301 of file ChartContainer.cpp.
References CPointFromPntF(), MODE_ZOOMINGX, and MODE_ZOOMINGY.
bool CChartContainer::ShowAxisXBoundaries (bool bSet, bool bRedraw = false)
Definition at line 2590 of file ChartContainer.cpp.
bool CChartContainer::ShowChartPoints (int chartIdx, bool bShow, bool bRedraw = false)
Definition at line 2700 of file ChartContainer.cpp.
References CChart::AllowPnts(), CChart::GetMaxValX(), CChart::GetMaxValY(), CChart::GetMinValX(), CChart::GetMinValY(), and CChart::IsChartVisible().
CDataWnd * CChartContainer::ShowDataLegend (double dataLegX)
Definition at line 2625 of file ChartContainer.cpp.
References CHART_DTPNTSZ, CPointFromPntF(), and CDataWnd::m_mapLabs.
CDataWnd * CChartContainer::ShowDataLegend (CPoint pnt) protected
Definition at line 2599 of file ChartContainer.cpp.
References CDataWnd::CreateLegend().
bool CChartContainer::ShowDataView (const string_t & szChartName, bool bRefresh)
Definition at line 3299 of file ChartContainer.cpp.
bool CChartContainer::ShowDataView (CChart * chartPtr, bool bClearMap, bool bRefresh = true) protected
Definition at line 3229 of file ChartContainer.cpp.
References DV_RECTH, DV_RECTW, DV_SPACE, CChart::GetChartIdx(), and CChart::m_vDataPnts.
CDataWnd * CChartContainer::ShowNamesLegend (void)
Definition at line 2666 of file ChartContainer.cpp.
References CDataWnd::m_mapLabs.
int CChartContainer::ToggleChartVisibility (int chartIdx)
Definition at line 1274 of file ChartContainer.cpp.
References CChart::HasData(), CChart::IsChartSelected(), CChart::SelectChart(), and CChart::ToggleChartVisibility().
bool CChartContainer::TruncateChart (int chartIdx, double startX, double endX, bool bUpdateExt = false, bool bRedraw = false)
Definition at line 2465 of file ChartContainer.cpp.
References F_TRUNCATE, CChart::GetChartIdx(), CChart::HasData(), and CChart::TruncateChartData().
void CChartContainer::UndoHistStepX (bool bRedraw = false)
Definition at line 833 of file ChartContainer.cpp.
References MODE_FULLX, and MODE_ZOOMEDX.
void CChartContainer::UndoHistStepY (bool bRedraw = false)
Definition at line 858 of file ChartContainer.cpp.
References MODE_FULLY, MODE_MOVEDY, and MODE_ZOOMEDY.
bool CChartContainer::UnwindHistX (double minX, double maxX)
Definition at line 891 of file ChartContainer.cpp.
bool CChartContainer::UpdateChartLocScaleY (int chartIdx, double locScY, bool bVisibleOnly, bool bRedraw = false)
Definition at line 1794 of file ChartContainer.cpp.
References CChart::GetLocScaleY(), CChart::HasData(), CChart::IsChartVisible(), and CChart::SetLocScaleY().
bool CChartContainer::UpdateChartPenWidth (int chartIdx, float penWidth, bool bVisibleOnly, bool bRedraw = false)
Definition at line 1316 of file ChartContainer.cpp.
References CChart::GetPenWidth(), CChart::IsChartVisible(), and CChart::SetPenWidth().
void CChartContainer::UpdateContainerWnds (int chartIdx = -1, bool bMatrix = false, DATAVIEW_FLAGS dataChange = F_NODATACHANGE)
Definition at line 2795 of file ChartContainer.cpp.
void CChartContainer::UpdateDataLegend (bool bChangeMatrix) protected
Definition at line 2726 of file ChartContainer.cpp.
size_t CChartContainer::UpdateDataLegend (MAP_SELPNTSD & mapSelPntsD, MAP_LABSTR & m_mapLabs) protected
Definition at line 3126 of file ChartContainer.cpp.
References CPointFromPntF(), CChart::GetLocScaleY(), CChart::GetSelValString(), in_range(), CChart::IsChartVisible(), PointT< T >::X, and PointT< T >::Y.
bool CChartContainer::UpdateDataView (int chartIdx, DATAVIEW_FLAGS flagsData) protected
Definition at line 3316 of file ChartContainer.cpp.
References CChart::IsChartVisible().
void CChartContainer::UpdateDataViewPnts (int chartIdx, size_t dataID, PointD dataPntD, bool bAdd)
Definition at line 5344 of file ChartContainer.cpp.
Referenced by CChartDataView::RefreshSelCells(), and CChartDataView::UpdateDataIdx().
void CChartContainer::UpdateDataViewPnts (int chartIdx, const MAP_SELPNTSD & mapSelPntsD)
Definition at line 5382 of file ChartContainer.cpp.
size_t CChartContainer::UpdateDataViewPntsDMap (void) protected
Definition at line 3330 of file ChartContainer.cpp.
void CChartContainer::UpdateExtX (double minExtX, double maxExtX, bool bRedraw = false)
Definition at line 417 of file ChartContainer.cpp.
void CChartContainer::UpdateExtY (double minExtY, double maxExtY, bool bRedraw = false)
Definition at line 460 of file ChartContainer.cpp.
PAIR_DBLS CChartContainer::UpdateScales (const RectF drawRectF, double minX, double maxX, double minY, double maxY) protected
Definition at line 2913 of file ChartContainer.cpp.
References MODE_FULLY, MODE_MOVEDY, and MODE_MOVEY.
Referenced by PrintCharts().
double CChartContainer::UpdateScaleX (const float drawRectWidth, double startX, double endX) protected
Definition at line 2890 of file ChartContainer.cpp.
double CChartContainer::UpdateScaleY (const float drawRectHeight, double minY, double maxY) protected
Definition at line 2901 of file ChartContainer.cpp.
CH_MODE CChartContainer::ZoomContainerX (double startX, double endX, bool bRedraw = false) protected
Definition at line 1857 of file ChartContainer.cpp.
References MODE_FULLX, MODE_ZOOMEDX, and MODE_ZOOMX.
CH_MODE CChartContainer::ZoomContainerY (double startY, double endY, bool bRedraw = false) protected
Definition at line 1935 of file ChartContainer.cpp.
References MODE_ZOOMEDY.
bool CChartContainer::ZoomMoveContainerX (double startX, double endX, bool bRedraw)
Definition at line 1830 of file ChartContainer.cpp.
References in_range(), and MODE_ZOOMX.
bool CChartContainer::ZoomMoveContainerY (double startY, double endY, bool bMoving, bool bRedraw)
Definition at line 1899 of file ChartContainer.cpp.
References MODE_FULLY, MODE_MOVEDY, MODE_MOVEY, MODE_ZOOMEDY, and MODE_ZOOMY.
Friends And Related Function Documentation
friend class CDataView friend
Definition at line 38 of file ChartContainer.h.
Member Data Documentation
float CChartContainer::m_axOffsXF protected
Definition at line 502 of file ChartContainer.h.
AX_XPOS CChartContainer::m_axXPos protected
Definition at line 503 of file ChartContainer.h.
Referenced by PrintCharts().
AX_YPOS CChartContainer::m_axYPos protected
Definition at line 504 of file ChartContainer.h.
Referenced by PrintCharts().
bool CChartContainer::m_bAxBoundaries protected
Definition at line 510 of file ChartContainer.h.
Referenced by CloneChartContainer(), operator=(), and PrintCharts().
bool CChartContainer::m_bHasNamesLeg protected
Definition at line 508 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
bool CChartContainer::m_bTracking protected
Definition at line 507 of file ChartContainer.h.
Referenced by CloneChartContainer(), operator=(), and PrintCharts().
bool CChartContainer::m_bUserEnabled protected
Definition at line 509 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
int CChartContainer::m_chartSelIdx protected
Definition at line 511 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
CH_MODE CChartContainer::m_chModeX protected
Definition at line 535 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
CH_MODE CChartContainer::m_chModeY protected
Definition at line 536 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
Color CChartContainer::m_colAxis protected
Definition at line 490 of file ChartContainer.h.
Referenced by CloneChartContainer(), operator=(), and PrintCharts().
Color CChartContainer::m_colBkground protected
Definition at line 488 of file ChartContainer.h.
Referenced by CloneChartContainer(), operator=(), and PrintCharts().
Color CChartContainer::m_colBorder protected
Definition at line 489 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
Color CChartContainer::m_colDataViewPnts protected
Definition at line 493 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
Color CChartContainer::m_colGrid protected
Definition at line 496 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
Color CChartContainer::m_colLegBkgnd protected
Definition at line 494 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
Color CChartContainer::m_colLegBorder protected
Definition at line 495 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
Color CChartContainer::m_colLegPnts protected
Definition at line 492 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
Color CChartContainer::m_colZoomBorder protected
Definition at line 491 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
PointD CChartContainer::m_dataLegPntD protected
Definition at line 520 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
int CChartContainer::m_dataViewChartIdx protected
Definition at line 512 of file ChartContainer.h.
double CChartContainer::m_endX protected
Definition at line 501 of file ChartContainer.h.
Referenced by CloneChartContainer(), operator=(), and PrintCharts().
double CChartContainer::m_epsX protected
Definition at line 521 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
string_t CChartContainer::m_labelX protected
Definition at line 538 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
MAP_CHARTS CChartContainer::m_mapCharts protected
Definition at line 526 of file ChartContainer.h.
Referenced by CloneChartContainer(), operator=(), and PrintCharts().
MAP_SELPNTSD CChartContainer::m_mapDataViewPntsD protected
Definition at line 528 of file ChartContainer.h.
MAP_SELPNTSD CChartContainer::m_mapSelPntsD protected
Definition at line 527 of file ChartContainer.h.
Referenced by CloneChartContainer(), operator=(), and PrintCharts().
double CChartContainer::m_maxExtY protected
Definition at line 499 of file ChartContainer.h.
Referenced by CloneChartContainer(), operator=(), and PrintCharts().
double CChartContainer::m_minExtY protected
Definition at line 498 of file ChartContainer.h.
Referenced by CloneChartContainer(), operator=(), and PrintCharts().
string_t CChartContainer::m_name protected
Definition at line 537 of file ChartContainer.h.
Referenced by CloneChartContainer(), operator=(), PrintCharts(), and PrintPageHeader().
CChartDataView* CChartContainer::m_pChartDataView protected
Definition at line 532 of file ChartContainer.h.
CDataWnd* CChartContainer::m_pDataWnd protected
Definition at line 530 of file ChartContainer.h.
val_label_str_fn CChartContainer::m_pLabValStrFnPtr protected
Definition at line 540 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
CDataWnd* CChartContainer::m_pLegWnd protected
Definition at line 531 of file ChartContainer.h.
MatrixD* CChartContainer::m_pMatrixD protected
Definition at line 518 of file ChartContainer.h.
Referenced by PrintCharts().
int CChartContainer::m_precision protected
Definition at line 513 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
double CChartContainer::m_scX protected
Definition at line 505 of file ChartContainer.h.
Referenced by PrintCharts().
double CChartContainer::m_scY protected
Definition at line 506 of file ChartContainer.h.
Referenced by PrintCharts().
double CChartContainer::m_startX protected
Definition at line 500 of file ChartContainer.h.
Referenced by CloneChartContainer(), operator=(), and PrintCharts().
double CChartContainer::m_tmpZX protected
Definition at line 515 of file ChartContainer.h.
double CChartContainer::m_tmpZY protected
Definition at line 516 of file ChartContainer.h.
V_HIST CChartContainer::m_vHistX protected
Definition at line 524 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
V_HIST CChartContainer::m_vHistY protected
Definition at line 525 of file ChartContainer.h.
Referenced by CloneChartContainer(), and operator=().
The documentation for this class was generated from the following files:
C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/ChartContainer.h
C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/ChartContainer.cpp