ChartContainerLib: MatrixD Class Reference
MatrixD Class Reference
#include <ChartDef.h>
Public Member Functions
MatrixD (double scX=1.0, double scY=1.0, double offsX=0.0, double offsY=0.0)
void Translate (double offsX, double offsY)
void Scale (double scX, double scY)
bool Invert (void)
MatrixD * Clone (void)
Gdiplus::PointF TransformToPntF (double locScY, const PointD &pntD)
PointD TransformToPntD (double locScY, const Gdiplus::PointF &pntF)
Public Attributes
double m_scX
double m_scY
double m_offsX
double m_offsY
Detailed Description
Definition at line 51 of file ChartDef.h.
Constructor & Destructor Documentation
MatrixD::MatrixD (double scX = 1.0, double scY = 1.0, double offsX = 0.0, double offsY = 0.0) inline
Definition at line 60 of file ChartDef.h.
Referenced by Clone().
Member Function Documentation
MatrixD* MatrixD::Clone (void) inline
Definition at line 81 of file ChartDef.h.
References m_offsX, m_offsY, m_scX, m_scY, and MatrixD().
Referenced by CChartContainer::DrawContainerToBmp(), CChartContainer::GetTransformMatrixD(), CChartContainer::OnPaint(), CChartContainer::PrintCharts(), reverse_transform_and_cast_to_pntD::reverse_transform_and_cast_to_pntD(), CChartContainer::SetTransformMatrixD(), and TransformToPntD().
bool MatrixD::Invert (void) inline
Definition at line 69 of file ChartDef.h.
References m_offsX, m_offsY, m_scX, and m_scY.
Referenced by reverse_transform_and_cast_to_pntD::reverse_transform_and_cast_to_pntD(), and TransformToPntD().
void MatrixD::Scale (double scX, double scY) inline
Definition at line 66 of file ChartDef.h.
References m_scX, and m_scY.
Referenced by CChartContainer::DrawContainerToBmp(), CChartContainer::GetTransformMatrixD(), CChartContainer::OnPaint(), and CChartContainer::PrintCharts().
PointD MatrixD::TransformToPntD (double locScY, const Gdiplus::PointF & pntF) inline
Definition at line 100 of file ChartDef.h.
References Clone(), Invert(), m_offsX, m_offsY, m_scX, and m_scY.
Referenced by CChartContainer::MousePntToPntD().
Gdiplus::PointF MatrixD::TransformToPntF (double locScY, const PointD & pntD) inline
Definition at line 92 of file ChartDef.h.
References m_offsX, m_offsY, m_scX, m_scY, PointT< T >::X, and PointT< T >::Y.
void MatrixD::Translate (double offsX, double offsY) inline
Definition at line 64 of file ChartDef.h.
References m_offsX, m_offsY, m_scX, and m_scY.
Referenced by CChartContainer::DrawContainerToBmp(), CChartContainer::GetTransformMatrixD(), CChartContainer::OnPaint(), and CChartContainer::PrintCharts().
Member Data Documentation
double MatrixD::m_offsX
Definition at line 56 of file ChartDef.h.
Referenced by Clone(), Invert(), transform_and_cast_to_pntF::operator()(), reverse_transform_and_cast_to_pntD::operator()(), TransformToPntD(), TransformToPntF(), and Translate().
double MatrixD::m_offsY
Definition at line 57 of file ChartDef.h.
Referenced by Clone(), Invert(), transform_and_cast_to_pntF::operator()(), reverse_transform_and_cast_to_pntD::operator()(), TransformToPntD(), TransformToPntF(), and Translate().
double MatrixD::m_scX
Definition at line 54 of file ChartDef.h.
Referenced by Clone(), Invert(), transform_and_cast_to_pntF::operator()(), reverse_transform_and_cast_to_pntD::operator()(), Scale(), TransformToPntD(), TransformToPntF(), and Translate().
double MatrixD::m_scY
Definition at line 55 of file ChartDef.h.
Referenced by Clone(), Invert(), transform_and_cast_to_pntF::operator()(), reverse_transform_and_cast_to_pntD::operator()(), Scale(), TransformToPntD(), TransformToPntF(), and Translate().
The documentation for this class was generated from the following file:
C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/ChartDef.h