ChartContainerLib: CChart Class Reference
CChart Class Reference
#include <Chart.h>
Public Member Functions
CChart (void)
~CChart (void)
CChart * CloneChart (bool bCloneState=false)
int GetChartIdx (void) const
string_t GetChartName (void) const
void SetChartName (string_t name)
string_t GetAxisYName (void) const
void SetAxisYName (string_t labelY)
val_label_str_fn GetLabYValStrFnPtr (void) const
void SetLabYValStrFn (val_label_str_fn pLabYValStrFn)
bool IsChartVisible () const
void SetChartVisibility (bool bVisible)
bool ToggleChartVisibility ()
bool IsChartSelected () const
void SelectChart (bool bSel)
bool ArePntsAllowed (void) const
void AllowPnts (bool bAllowed)
Color GetChartColor (void) const
void SetChartColor (Color colChart)
DashStyle GetChartDashStyle (void) const
void SetDashStyle (DashStyle dashStyle)
float GetTension (void) const
void SetTension (float fTension)
float GetPenWidth (void) const
void SetPenWidth (float penWidth)
double GetMinValX (void) const
void SetMinValX (double fMinValX)
double GetMaxValX (void) const
void SetMaxValX (double fMaxValX)
double GetMinValY (void) const
void SetMinValY (double fMinValY)
double GetMaxValY (void) const
void SetMaxValY (double fMaxValY)
int GetPrecisionY (void) const
void SetPrecisionY (int precisionY)
double GetLocScaleY (void) const
void SetLocScaleY (double locScaleY)
size_t GetDataSize () const
bool HasData (void) const
void ResetChartData (void)
void SetChartAttr (bool bVisible, bool bShowPnts, int idx, string_t label, string_t labelY, int precisionY, DashStyle dashStyle, float penWidth, float tension, Color col)
PAIR_ITS GetStartEndDataIterators (V_CHARTDATAD &vDataPnts, double startX, double endX)
size_t AppendChartData (V_CHARTDATAD &vData)
bool TruncateChartData (double startX, double endX)
PAIR_ITNEAREST GetNearestPointD (const PointD &origPntD, double dist, PointD &selPnt)
TUPLE_LABEL GetSelValString (const PointD selPntD, string_t nameX, int precision, val_label_str_fn pLabXValStrFnPtr)
bool DrawChartCurve (V_CHARTDATAD &vDataPnts, double startX, double endX, MatrixD *pMatrixD, GraphicsPath *grPathPtr, Graphics *grPtr, float dpiRatio=1.0f)
bool ConvertChartData (V_CHARTDATAD &vDataPnts, V_CHARTDATAF &vChDatF, MatrixD *pMatrixD, double startX, double endX)
bool GetVisibleChartNameAndVisuals (TUPLE_LABEL &tuple_res)
Public Attributes
V_CHARTDATAD m_vDataPnts
Protected Attributes
bool m_bVisible
bool m_bSelected
bool m_bShowPnts
int m_nIdx
Color m_colChart
DashStyle m_dashStyle
float m_fPenWidth
float m_fTension
double m_fMinValX
double m_fMaxValX
double m_fMinValY
double m_fMaxValY
int m_precisionY
double m_fLocScaleY
string_t m_label
string_t m_labelY
val_label_str_fn m_pLabYValStrFn
Detailed Description
Definition at line 21 of file Chart.h.
Constructor & Destructor Documentation
CChart::CChart (void)
Definition at line 32 of file Chart.cpp.
Referenced by CloneChart().
CChart::~CChart (void)
Definition at line 42 of file Chart.cpp.
Member Function Documentation
void CChart::AllowPnts (bool bAllowed) inline
Definition at line 55 of file Chart.h.
Referenced by CChartContainer::AllowChartPnts(), CChartContainer::OnMnShowPnts(), and CChartContainer::ShowChartPoints().
size_t CChart::AppendChartData (V_CHARTDATAD & vData)
Definition at line 109 of file Chart.cpp.
References m_fMaxValX, m_fMaxValY, m_fMinValX, m_fMinValY, m_vDataPnts, PointT< T >::X, and PointT< T >::Y.
Referenced by CChartContainer::AppendChartData().
bool CChart::ArePntsAllowed (void) const inline
Definition at line 54 of file Chart.h.
Referenced by CChartContainer::AllowChartPnts(), CChartContainer::OnContextMenu(), and CChartContainer::OnMnShowPnts().
CChart * CChart::CloneChart (bool bCloneState = false)
Definition at line 46 of file Chart.cpp.
References CChart(), m_bSelected, m_bShowPnts, m_bVisible, m_colChart, m_dashStyle, m_fLocScaleY, m_fMaxValX, m_fMaxValY, m_fMinValX, m_fMinValY, m_fPenWidth, m_fTension, m_label, m_labelY, m_nIdx, m_pLabYValStrFn, m_precisionY, and m_vDataPnts.
Referenced by CChartContainer::CloneChart(), CChartContainer::CloneChartContainer(), and CChartContainer::operator=().
bool CChart::ConvertChartData (V_CHARTDATAD & vDataPnts, V_CHARTDATAF & vChDatF, MatrixD * pMatrixD, double startX, double endX)
Definition at line 325 of file Chart.cpp.
References GetStartEndDataIterators(), and m_fLocScaleY.
Referenced by DrawChartCurve(), CChartContainer::DrawDataViewPntsD(), and CChartContainer::SelectChartByMouseClick().
bool CChart::DrawChartCurve (V_CHARTDATAD & vDataPnts, double startX, double endX, MatrixD * pMatrixD, GraphicsPath * grPathPtr, Graphics * grPtr, float dpiRatio = 1.0f)
Definition at line 234 of file Chart.cpp.
References ALPHA_NOPNT, ALPHA_SELECT, CHART_DTPNTSZ, CHART_PNTSTRSH, ConvertChartData(), m_bSelected, m_bShowPnts, m_colChart, m_dashStyle, m_fPenWidth, m_fTension, PEN_SELWIDTH, RectFFromCenterF(), and SetAlpha().
Referenced by CChartContainer::DrawContainerToBmp(), CChartContainer::OnPaint(), and CChartContainer::PrintCharts().
string_t CChart::GetAxisYName (void) const inline
Definition at line 37 of file Chart.h.
Referenced by CChartsXMLSerializer::ChartDataToXML(), CChartContainer::GetSelValString(), CChartDataView::InitParams(), and CChartDataView::UpdateParams().
Color CChart::GetChartColor (void) const inline
Definition at line 58 of file Chart.h.
Referenced by CChartsXMLSerializer::ChartDataToXML(), CChartContainer::GetSelValString(), and CChartContainer::SetChartColor().
DashStyle CChart::GetChartDashStyle (void) const inline
Definition at line 62 of file Chart.h.
Referenced by CChartsXMLSerializer::ChartDataToXML(), CChartContainer::GetSelValString(), and CChartContainer::SetChartDashStyle().
int CChart::GetChartIdx (void) const inline
Definition at line 32 of file Chart.h.
Referenced by CChartContainer::AddChart(), CChartContainer::ChangeLocScaleYByArrowKeys(), CChartContainer::CloneChartContainer(), CChartContainer::DrawSelPntsD(), CChartContainer::GetChartIdx(), CChartContainer::GetSelValString(), CChartContainer::HasChartDifferentPnts(), CChartDataView::InitParams(), CChartContainer::PrepareDataLegend(), CChartContainer::SelectChart(), CChartContainer::SelectChartByMouseClick(), CChartContainer::ShowDataView(), CChartContainer::TruncateChart(), and CChartDataView::UpdateParams().
string_t CChart::GetChartName (void) const inline
Definition at line 34 of file Chart.h.
Referenced by CChartsXMLSerializer::ChartDataToXML(), CChartContainer::GetSelValString(), CChartDataView::InitParams(), and CChartDataView::UpdateParams().
size_t CChart::GetDataSize () const inline
Definition at line 94 of file Chart.h.
val_label_str_fn CChart::GetLabYValStrFnPtr (void) const inline
Definition at line 40 of file Chart.h.
Referenced by CChartsXMLSerializer::ChartDataToXML(), CChartContainer::GetSelValString(), CChartDataView::InitParams(), and CChartDataView::UpdateParams().
double CChart::GetLocScaleY (void) const inline
Definition at line 91 of file Chart.h.
Referenced by CChartContainer::DrawSelLine(), CChartContainer::DrawSelPntsD(), CChartContainer::GetLocScYDelta(), CChartContainer::GetSelValString(), CChartContainer::HasVisiblePntsDInYBand(), CChartContainer::PrepareDataLegend(), CChartContainer::UpdateChartLocScaleY(), and CChartContainer::UpdateDataLegend().
double CChart::GetMaxValX (void) const inline
Definition at line 77 of file Chart.h.
Referenced by CChartContainer::AddChart(), CChartContainer::AppendChartData(), CChartsXMLSerializer::ChartDataToXML(), CChartContainer::GetMinMaxExtX(), CChartContainer::HasChartDifferentPnts(), and CChartContainer::ShowChartPoints().
double CChart::GetMaxValY (void) const inline
Definition at line 83 of file Chart.h.
Referenced by CChartContainer::AddChart(), CChartContainer::AppendChartData(), CChartsXMLSerializer::ChartDataToXML(), CChartContainer::EqualizeVertRanges(), CChartContainer::GetLocScYDelta(), CChartContainer::GetMinMaxExtY(), CChartContainer::GetSelValString(), CChartContainer::HasChartDifferentPnts(), and CChartContainer::ShowChartPoints().
double CChart::GetMinValX (void) const inline
Definition at line 74 of file Chart.h.
Referenced by CChartContainer::AddChart(), CChartContainer::AppendChartData(), CChartsXMLSerializer::ChartDataToXML(), CChartContainer::GetMinMaxExtX(), CChartContainer::HasChartDifferentPnts(), and CChartContainer::ShowChartPoints().
double CChart::GetMinValY (void) const inline
Definition at line 80 of file Chart.h.
Referenced by CChartContainer::AddChart(), CChartContainer::AppendChartData(), CChartsXMLSerializer::ChartDataToXML(), CChartContainer::EqualizeVertRanges(), CChartContainer::GetLocScYDelta(), CChartContainer::GetMinMaxExtY(), CChartContainer::GetSelValString(), CChartContainer::HasChartDifferentPnts(), and CChartContainer::ShowChartPoints().
PAIR_ITNEAREST CChart::GetNearestPointD (const PointD & origPntD, double dist, PointD & selPnt)
Definition at line 190 of file Chart.cpp.
References find_nearest(), m_vDataPnts, and PointT< T >::X.
Referenced by CChartContainer::PrepareDataLegend().
float CChart::GetPenWidth (void) const inline
Definition at line 70 of file Chart.h.
Referenced by CChartsXMLSerializer::ChartDataToXML(), CChartContainer::GetSelValString(), and CChartContainer::UpdateChartPenWidth().
int CChart::GetPrecisionY (void) const inline
Definition at line 87 of file Chart.h.
Referenced by CChartsXMLSerializer::ChartDataToXML(), CChartContainer::GetSelValString(), CChartDataView::InitParams(), and CChartDataView::UpdateParams().
TUPLE_LABEL CChart::GetSelValString (const PointD selPntD, string_t nameX, int precision, val_label_str_fn pLabXValStrFnPtr)
Definition at line 212 of file Chart.cpp.
References ALPHA_MINFORLABEL, m_colChart, m_dashStyle, m_fPenWidth, m_label, m_labelY, m_pLabYValStrFn, m_precisionY, SetAlpha(), PointT< T >::X, and PointT< T >::Y.
Referenced by CChartContainer::PrepareDataLegend(), and CChartContainer::UpdateDataLegend().
PAIR_ITS CChart::GetStartEndDataIterators (V_CHARTDATAD & vDataPnts, double startX, double endX)
Definition at line 102 of file Chart.cpp.
References find_border_pnts().
Referenced by ConvertChartData(), CChartContainer::HasVisiblePntsDInYBand(), and TruncateChartData().
float CChart::GetTension (void) const inline
Definition at line 66 of file Chart.h.
Referenced by CChartsXMLSerializer::ChartDataToXML().
bool CChart::GetVisibleChartNameAndVisuals (TUPLE_LABEL & tuple_res)
Definition at line 350 of file Chart.cpp.
References HasData(), m_bVisible, m_colChart, m_dashStyle, m_fPenWidth, m_label, and SetAlpha().
bool CChart::HasData (void) const inline
Definition at line 96 of file Chart.h.
Referenced by CChartsXMLSerializer::ChartDataToXML(), CChartContainer::GetVisibleChart(), GetVisibleChartNameAndVisuals(), CChartContainer::SelectChartByMouseClick(), CChartContainer::ToggleChartVisibility(), CChartContainer::TruncateChart(), TruncateChartData(), CChartContainer::UpdateChartLocScaleY(), and CChartDataView::UpdateParams().
bool CChart::IsChartSelected () const inline
Definition at line 50 of file Chart.h.
Referenced by CChartContainer::ChangeLocScaleYByArrowKeys(), CChartContainer::OnMouseWheel(), and CChartContainer::ToggleChartVisibility().
bool CChart::IsChartVisible () const inline
Definition at line 45 of file Chart.h.
Referenced by CChartContainer::AllowChartPnts(), CChartContainer::AppendChartData(), CChartContainer::ChangeLocScaleYByArrowKeys(), CChartsXMLSerializer::ChartDataToXML(), CChartContainer::DrawContainerToBmp(), CChartContainer::DrawDataViewPntsD(), CChartContainer::GetChart(), CChartContainer::GetVisibleChart(), CChartContainer::HasChartDifferentPnts(), CChartContainer::HasVisiblePntsDInYBand(), CChartContainer::OnMouseWheel(), CChartContainer::OnPaint(), CChartContainer::PrepareDataLegend(), CChartContainer::PrintCharts(), CChartContainer::ResetCharts(), CChartContainer::SelectChartByMouseClick(), CChartContainer::SetChartColor(), CChartContainer::SetChartDashStyle(), CChartContainer::ShowChartPoints(), CChartContainer::UpdateChartLocScaleY(), CChartContainer::UpdateChartPenWidth(), CChartContainer::UpdateDataLegend(), and CChartContainer::UpdateDataView().
void CChart::ResetChartData (void) inline
Definition at line 98 of file Chart.h.
void CChart::SelectChart (bool bSel) inline
Definition at line 51 of file Chart.h.
Referenced by CChartContainer::SelectChart(), and CChartContainer::ToggleChartVisibility().
void CChart::SetAxisYName (string_t labelY) inline
Definition at line 38 of file Chart.h.
void CChart::SetChartAttr (bool bVisible, bool bShowPnts, int idx, string_t label, string_t labelY, int precisionY, DashStyle dashStyle, float penWidth, float tension, Color col)
Definition at line 86 of file Chart.cpp.
References m_bShowPnts, m_bVisible, m_colChart, m_dashStyle, m_fPenWidth, m_fTension, m_label, m_labelY, m_nIdx, and m_precisionY.
Referenced by CChartContainer::AddChart().
void CChart::SetChartColor (Color colChart) inline
Definition at line 59 of file Chart.h.
Referenced by CChartContainer::SetChartColor().
void CChart::SetChartName (string_t name) inline
Definition at line 35 of file Chart.h.
void CChart::SetChartVisibility (bool bVisible) inline
Definition at line 46 of file Chart.h.
void CChart::SetDashStyle (DashStyle dashStyle) inline
Definition at line 63 of file Chart.h.
Referenced by CChartContainer::SetChartDashStyle().
void CChart::SetLabYValStrFn (val_label_str_fn pLabYValStrFn) inline
Definition at line 41 of file Chart.h.
void CChart::SetLocScaleY (double locScaleY) inline
Definition at line 92 of file Chart.h.
Referenced by CChartContainer::ChangeLocScaleYByArrowKeys(), CChartContainer::OnMouseWheel(), CChartContainer::ReplaceChartData(), CChartContainer::ResetCharts(), and CChartContainer::UpdateChartLocScaleY().
void CChart::SetMaxValX (double fMaxValX) inline
Definition at line 78 of file Chart.h.
Referenced by CChartContainer::AddChart(), and CChartContainer::ReplaceChartData().
void CChart::SetMaxValY (double fMaxValY) inline
Definition at line 84 of file Chart.h.
Referenced by CChartContainer::AddChart(), and CChartContainer::ReplaceChartData().
void CChart::SetMinValX (double fMinValX) inline
Definition at line 75 of file Chart.h.
Referenced by CChartContainer::AddChart(), and CChartContainer::ReplaceChartData().
void CChart::SetMinValY (double fMinValY) inline
Definition at line 81 of file Chart.h.
Referenced by CChartContainer::AddChart(), and CChartContainer::ReplaceChartData().
void CChart::SetPenWidth (float penWidth) inline
Definition at line 71 of file Chart.h.
Referenced by CChartContainer::UpdateChartPenWidth().
void CChart::SetPrecisionY (int precisionY) inline
Definition at line 88 of file Chart.h.
void CChart::SetTension (float fTension) inline
Definition at line 67 of file Chart.h.
bool CChart::ToggleChartVisibility () inline
Definition at line 47 of file Chart.h.
Referenced by CChartContainer::ResetCharts(), and CChartContainer::ToggleChartVisibility().
bool CChart::TruncateChartData (double startX, double endX)
Definition at line 150 of file Chart.cpp.
References GetStartEndDataIterators(), HasData(), m_fMaxValX, m_fMaxValY, m_fMinValX, m_fMinValY, and m_vDataPnts.
Referenced by CChartContainer::TruncateChart().
Member Data Documentation
bool CChart::m_bSelected protected
Definition at line 128 of file Chart.h.
Referenced by CloneChart(), and DrawChartCurve().
bool CChart::m_bShowPnts protected
Definition at line 129 of file Chart.h.
Referenced by CloneChart(), DrawChartCurve(), and SetChartAttr().
bool CChart::m_bVisible protected
Definition at line 127 of file Chart.h.
Referenced by CloneChart(), GetVisibleChartNameAndVisuals(), and SetChartAttr().
Color CChart::m_colChart protected
Definition at line 132 of file Chart.h.
Referenced by CloneChart(), DrawChartCurve(), GetSelValString(), GetVisibleChartNameAndVisuals(), and SetChartAttr().
DashStyle CChart::m_dashStyle protected
Definition at line 133 of file Chart.h.
Referenced by CloneChart(), DrawChartCurve(), GetSelValString(), GetVisibleChartNameAndVisuals(), and SetChartAttr().
double CChart::m_fLocScaleY protected
Definition at line 143 of file Chart.h.
Referenced by CloneChart(), and ConvertChartData().
double CChart::m_fMaxValX protected
Definition at line 138 of file Chart.h.
Referenced by AppendChartData(), CloneChart(), and TruncateChartData().
double CChart::m_fMaxValY protected
Definition at line 140 of file Chart.h.
Referenced by AppendChartData(), CloneChart(), and TruncateChartData().
double CChart::m_fMinValX protected
Definition at line 137 of file Chart.h.
Referenced by AppendChartData(), CloneChart(), and TruncateChartData().
double CChart::m_fMinValY protected
Definition at line 139 of file Chart.h.
Referenced by AppendChartData(), CloneChart(), and TruncateChartData().
float CChart::m_fPenWidth protected
Definition at line 134 of file Chart.h.
Referenced by CloneChart(), DrawChartCurve(), GetSelValString(), GetVisibleChartNameAndVisuals(), and SetChartAttr().
float CChart::m_fTension protected
Definition at line 135 of file Chart.h.
Referenced by CloneChart(), DrawChartCurve(), and SetChartAttr().
string_t CChart::m_label protected
Definition at line 145 of file Chart.h.
Referenced by CloneChart(), GetSelValString(), GetVisibleChartNameAndVisuals(), and SetChartAttr().
string_t CChart::m_labelY protected
Definition at line 146 of file Chart.h.
Referenced by CloneChart(), GetSelValString(), and SetChartAttr().
int CChart::m_nIdx protected
Definition at line 131 of file Chart.h.
Referenced by CloneChart(), and SetChartAttr().
val_label_str_fn CChart::m_pLabYValStrFn protected
Definition at line 147 of file Chart.h.
Referenced by CloneChart(), and GetSelValString().
int CChart::m_precisionY protected
Definition at line 142 of file Chart.h.
Referenced by CloneChart(), GetSelValString(), and SetChartAttr().
V_CHARTDATAD CChart::m_vDataPnts
Definition at line 150 of file Chart.h.
Referenced by CChartContainer::AddChart(), AppendChartData(), CChartsXMLSerializer::ChartDataToXML(), CloneChart(), CChartContainer::DrawContainerToBmp(), CChartContainer::ExportChartData(), CChartContainer::GetChartData(), GetNearestPointD(), CChartContainer::HasVisiblePntsDInYBand(), CChartDataView::InitParams(), CChartContainer::OnPaint(), CChartContainer::PrintCharts(), CChartContainer::ReplaceChartData(), CChartContainer::SelectChartByMouseClick(), CChartContainer::ShowDataView(), TruncateChartData(), and CChartDataView::UpdateParams().
The documentation for this class was generated from the following files:
C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/Chart.h
C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/Chart.cpp