ChartContainerLib: CDataWnd Class Reference
CDataWnd Class Reference
#include <DataLabel.h>
Public Member Functions
CDataWnd ()
CDataWnd (Color bkCol, Color borderCol)
virtual ~CDataWnd ()
afx_msg void OnPaint ()
bool IsDataLeg (void) const
string_t GetFontFamilyName () const
void SetFontFamilyName (string_t fontFamName)
int GetFontSize (void) const
void SetFontSize (int fontSize)
CRect GetDataWndRect (void) const
CRect GetDataWndStrRect (void) const
Color GetBkColor (void) const
void SetBkColor (Color bkCol, bool bRedraw=false)
Color GetBorderColor (void) const
void SetBorderColor (Color borderCol, bool bRedraw=false)
CRect GetLabWndRect (void) const
void DrawDataWnd (int OffsX, int offY, Graphics *grPtr)
bool CreateLegend (CWnd *pOwner)
bool CreateLegend (CWnd *pOwner, const CPoint origPnt, bool bData)
bool ShowLegendWnd (void)
bool UpdateDataLegend (MAP_LABSTR &mapLabStr, CWnd *pParent, CPoint origPnt)
Public Attributes
MAP_LABSTR m_mapLabs
Protected Member Functions
CRect CalcLabelStrRect (void)
CRect CalcNameWndRect (CRect labStrRect, CWnd *pParent)
CRect CalcDataWndRect (CRect &labStrRect, CWnd *pParent, CPoint origPnt)
float DrawLabel (const TUPLE_LABEL &tupleLabel, RectF labRect, Gdiplus::Font *pFont, Graphics *grPtr)
void DrawLabels (Graphics *grPtr, float offsXF=0.0f, float offsYF=0.0f)
void DrawLabelLine (RectF labelRectF, Color labCol, DashStyle dashStyle, float penWidth, Graphics *grPtr)
Protected Attributes
bool m_bData
string_t m_strFontFamilyName
int m_fontSize
float m_fOrigOffsX
float m_fBorderSpace
float m_fBulletSize
RectF m_strRF
RectF m_maxNameRF
RectF m_maxNameXRF
RectF m_maxXRF
RectF m_maxNameYRF
RectF m_maxYRF
CRect m_labelStrRect
CRect m_labelWndRect
Color m_colBkgnd
Color m_colBorder
Detailed Description
Definition at line 31 of file DataLabel.h.
Constructor & Destructor Documentation
CDataWnd::CDataWnd ()
Definition at line 24 of file DataLabel.cpp.
CDataWnd::CDataWnd (Color bkCol, Color borderCol)
Definition at line 31 of file DataLabel.cpp.
References m_strFontFamilyName.
CDataWnd::~CDataWnd () virtual
Definition at line 39 of file DataLabel.cpp.
Member Function Documentation
CRect CDataWnd::CalcDataWndRect (CRect & labStrRect, CWnd * pParent, CPoint origPnt) protected
Definition at line 153 of file DataLabel.cpp.
References LABEL_OFFS.
Referenced by CreateLegend(), and UpdateDataLegend().
CRect CDataWnd::CalcLabelStrRect (void) protected
Definition at line 57 of file DataLabel.cpp.
References m_bData, m_fBorderSpace, m_fontSize, m_fOrigOffsX, m_mapLabs, m_maxNameRF, m_maxNameXRF, m_maxNameYRF, m_maxXRF, m_maxYRF, m_strFontFamilyName, m_strRF, and RectFToCRect().
Referenced by CreateLegend(), and UpdateDataLegend().
CRect CDataWnd::CalcNameWndRect (CRect labStrRect, CWnd * pParent) protected
Definition at line 139 of file DataLabel.cpp.
References LABEL_OFFS.
Referenced by CreateLegend().
bool CDataWnd::CreateLegend (CWnd * pOwner)
Definition at line 191 of file DataLabel.cpp.
Referenced by CChartContainer::ShowDataLegend().
bool CDataWnd::CreateLegend (CWnd * pOwner, const CPoint origPnt, bool bData)
Definition at line 207 of file DataLabel.cpp.
References CalcDataWndRect(), CalcLabelStrRect(), CalcNameWndRect(), m_bData, m_labelStrRect, and m_labelWndRect.
void CDataWnd::DrawDataWnd (int OffsX, int offY, Graphics * grPtr)
Definition at line 384 of file DataLabel.cpp.
References CreateRoundedRect(), CRectToGdiRectF(), DrawLabels(), m_colBkgnd, m_colBorder, and m_labelStrRect.
float CDataWnd::DrawLabel (const TUPLE_LABEL & tupleLabel, RectF labRect, Gdiplus::Font * pFont, Graphics * grPtr) protected
Definition at line 269 of file DataLabel.cpp.
References DrawLabelLine(), m_bData, m_maxNameRF, m_maxNameXRF, m_maxNameYRF, m_maxXRF, and m_maxYRF.
Referenced by DrawLabels().
void CDataWnd::DrawLabelLine (RectF labelRectF, Color labCol, DashStyle dashStyle, float penWidth, Graphics * grPtr) protected
Definition at line 327 of file DataLabel.cpp.
References CHART_DTPNTSZ, m_fBorderSpace, and m_fBulletSize.
Referenced by DrawLabel().
void CDataWnd::DrawLabels (Graphics * grPtr, float offsXF = 0.0f, float offsYF = 0.0f) protected
Definition at line 363 of file DataLabel.cpp.
References DrawLabel(), m_fBorderSpace, m_fontSize, m_mapLabs, m_strFontFamilyName, and m_strRF.
Referenced by DrawDataWnd().
Color CDataWnd::GetBkColor (void) const inline
Definition at line 57 of file DataLabel.h.
Color CDataWnd::GetBorderColor (void) const inline
Definition at line 60 of file DataLabel.h.
CRect CDataWnd::GetDataWndRect (void) const inline
Definition at line 54 of file DataLabel.h.
CRect CDataWnd::GetDataWndStrRect (void) const inline
Definition at line 55 of file DataLabel.h.
string_t CDataWnd::GetFontFamilyName () const inline
Definition at line 47 of file DataLabel.h.
int CDataWnd::GetFontSize (void) const inline
Definition at line 51 of file DataLabel.h.
CRect CDataWnd::GetLabWndRect (void) const inline
Definition at line 64 of file DataLabel.h.
bool CDataWnd::IsDataLeg (void) const inline
Definition at line 45 of file DataLabel.h.
Referenced by CChartContainer::DestroyLabWnd().
void CDataWnd::OnPaint ()
Definition at line 416 of file DataLabel.cpp.
References CreateRoundedRect(), and GdiRectToRectF().
void CDataWnd::SetBkColor (Color bkCol, bool bRedraw = false)
Definition at line 43 of file DataLabel.cpp.
References m_colBkgnd.
void CDataWnd::SetBorderColor (Color borderCol, bool bRedraw = false)
Definition at line 50 of file DataLabel.cpp.
References m_colBorder.
void CDataWnd::SetFontFamilyName (string_t fontFamName) inline
Definition at line 48 of file DataLabel.h.
void CDataWnd::SetFontSize (int fontSize) inline
Definition at line 52 of file DataLabel.h.
bool CDataWnd::ShowLegendWnd (void)
Definition at line 236 of file DataLabel.cpp.
References m_labelWndRect, and m_mapLabs.
Referenced by UpdateDataLegend().
bool CDataWnd::UpdateDataLegend (MAP_LABSTR & mapLabStr, CWnd * pParent, CPoint origPnt)
Definition at line 251 of file DataLabel.cpp.
References CalcDataWndRect(), CalcLabelStrRect(), m_labelStrRect, m_labelWndRect, m_mapLabs, and ShowLegendWnd().
Member Data Documentation
bool CDataWnd::m_bData protected
Definition at line 91 of file DataLabel.h.
Referenced by CalcLabelStrRect(), CreateLegend(), and DrawLabel().
Color CDataWnd::m_colBkgnd protected
Definition at line 108 of file DataLabel.h.
Referenced by DrawDataWnd(), and SetBkColor().
Color CDataWnd::m_colBorder protected
Definition at line 109 of file DataLabel.h.
Referenced by DrawDataWnd(), and SetBorderColor().
float CDataWnd::m_fBorderSpace protected
Definition at line 96 of file DataLabel.h.
Referenced by CalcLabelStrRect(), DrawLabelLine(), and DrawLabels().
float CDataWnd::m_fBulletSize protected
Definition at line 97 of file DataLabel.h.
Referenced by DrawLabelLine().
int CDataWnd::m_fontSize protected
Definition at line 93 of file DataLabel.h.
Referenced by CalcLabelStrRect(), and DrawLabels().
float CDataWnd::m_fOrigOffsX protected
Definition at line 95 of file DataLabel.h.
Referenced by CalcLabelStrRect().
CRect CDataWnd::m_labelStrRect protected
Definition at line 105 of file DataLabel.h.
Referenced by CreateLegend(), DrawDataWnd(), and UpdateDataLegend().
CRect CDataWnd::m_labelWndRect protected
Definition at line 106 of file DataLabel.h.
Referenced by CreateLegend(), ShowLegendWnd(), and UpdateDataLegend().
MAP_LABSTR CDataWnd::m_mapLabs
Definition at line 88 of file DataLabel.h.
Referenced by CalcLabelStrRect(), DrawLabels(), CChartContainer::ShowDataLegend(), ShowLegendWnd(), CChartContainer::ShowNamesLegend(), and UpdateDataLegend().
RectF CDataWnd::m_maxNameRF protected
Definition at line 100 of file DataLabel.h.
Referenced by CalcLabelStrRect(), and DrawLabel().
RectF CDataWnd::m_maxNameXRF protected
Definition at line 101 of file DataLabel.h.
Referenced by CalcLabelStrRect(), and DrawLabel().
RectF CDataWnd::m_maxNameYRF protected
Definition at line 103 of file DataLabel.h.
Referenced by CalcLabelStrRect(), and DrawLabel().
RectF CDataWnd::m_maxXRF protected
Definition at line 102 of file DataLabel.h.
Referenced by CalcLabelStrRect(), and DrawLabel().
RectF CDataWnd::m_maxYRF protected
Definition at line 104 of file DataLabel.h.
Referenced by CalcLabelStrRect(), and DrawLabel().
string_t CDataWnd::m_strFontFamilyName protected
Definition at line 92 of file DataLabel.h.
Referenced by CalcLabelStrRect(), CDataWnd(), and DrawLabels().
RectF CDataWnd::m_strRF protected
Definition at line 99 of file DataLabel.h.
Referenced by CalcLabelStrRect(), and DrawLabels().
The documentation for this class was generated from the following files:
C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/DataLabel.h
C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/DataLabel.cpp