ChartContainerLib: CChartsXMLSerializer Class Reference
CChartsXMLSerializer Class Reference
#include <ChartsXMLSerializer.h>
Static Public Member Functions
static HRESULT ChartDataToXML (const _TCHAR *fileName, const CChartContainer *pContainer, const string_t chartName, bool bAll=false)
static HRESULT XMLToCharts (LPCTSTR fileName, CChartContainer *pContainer, const MAP_CHARTCOLS &mapCharts, bool bClearCharts)
static HRESULT GetChartNamesFromXMLFile (LPCTSTR fileName, MAP_CHARTCOLS &mapContent)
static HRESULT GetChartNamesFromXMLFile (LPCTSTR fileName, MAP_NAMES &mapNames)
static HRESULT ReplaceChartsFromXMLFile (LPCTSTR fileName, CChartContainer *pContainer)
Detailed Description
Definition at line 53 of file ChartsXMLSerializer.h.
Member Function Documentation
HRESULT CChartsXMLSerializer::ChartDataToXML (const _TCHAR * fileName, const CChartContainer * pContainer, const string_t chartName, bool bAll = false) static
Definition at line 31 of file ChartsXMLSerializer.cpp.
References CChartContainer::FindChart(), CChartContainer::GetAxisXName(), CChart::GetAxisYName(), CChart::GetChartColor(), CChart::GetChartDashStyle(), CChartContainer::GetChartIdx(), CChart::GetChartName(), CChartContainer::GetChartsEnd(), CChartContainer::GetContainerName(), CChartContainer::GetContainerPrecisionX(), CChartContainer::GetFirstChart(), CChartContainer::GetLabXValStrFnPtr(), CChart::GetLabYValStrFnPtr(), CChart::GetMaxValX(), CChart::GetMaxValY(), CChart::GetMinValX(), CChart::GetMinValY(), CChart::GetPenWidth(), CChart::GetPrecisionY(), CChart::GetTension(), CChart::HasData(), CChart::IsChartVisible(), CChartContainer::IsChartVisible(), CChartContainer::IsContainerEmpty(), CChart::m_vDataPnts, PointT< T >::X, and PointT< T >::Y.
Referenced by CChartContainer::SaveChartData().
HRESULT CChartsXMLSerializer::GetChartNamesFromXMLFile (LPCTSTR fileName, MAP_CHARTCOLS & mapContent) static
Definition at line 471 of file ChartsXMLSerializer.cpp.
References get_attrValue().
Referenced by CChartContainer::GetChartNamesFromXMLFile().
HRESULT CChartsXMLSerializer::GetChartNamesFromXMLFile (LPCTSTR fileName, MAP_NAMES & mapNames) static
Definition at line 596 of file ChartsXMLSerializer.cpp.
References get_attrValue().
HRESULT CChartsXMLSerializer::ReplaceChartsFromXMLFile (LPCTSTR fileName, CChartContainer * pContainer) static
Definition at line 720 of file ChartsXMLSerializer.cpp.
References CChartContainer::AddChart(), get_attrValue(), CChartContainer::ResetChartContainer(), CChartContainer::SetAxisXName(), CChartContainer::SetContainerName(), and CChartContainer::SetContainerPrecision().
Referenced by CChartContainer::ReplaceContainerCharts().
HRESULT CChartsXMLSerializer::XMLToCharts (LPCTSTR fileName, CChartContainer * pContainer, const MAP_CHARTCOLS & mapCharts, bool bClearCharts) static
Definition at line 233 of file ChartsXMLSerializer.cpp.
References CChartContainer::AddChart(), get_attrValue(), CChartContainer::GetMapCharts(), CChartContainer::SetAxisXName(), and CChartContainer::SetContainerPrecision().
Referenced by CChartContainer::LoadCharts().
The documentation for this class was generated from the following files:
C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/ChartsXMLSerializer.h
C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/ChartsXMLSerializer.cpp