ChartContainerLib: CChartDataView Class Reference
CChartDataView Class Reference
#include <ChartDataView.h>
Public Member Functions
CChartDataView ()
virtual ~CChartDataView ()
size_t GetPagesNmb (void) const
size_t GetCurrPageNmb (void) const
void InitParams (const CChart *chartPtr, bool bClearMap, const CChartContainer *pHost)
bool UpdateParams (const CChart *chartPtr, int flagsData)
size_t ChangeDataPage (int pageNmb)
void ShowWaitMessage (int chartIdx, size_t newSize)
size_t UpdateDataIdx (void)
size_t RefreshSelCells (void)
size_t PrintData (size_t nPage, Graphics *grPtr)
Public Attributes
V_CHARTDATAD m_vDataPnts
V_VALSTRINGS m_vStrX
V_VALSTRINGS m_vStrY
V_ROWS m_vRows
MAP_SELPNTSD m_mapSelCells
string_t m_fontName
float m_fontHeight
float m_headerFontHeight
RectF m_clipRF
size_t m_nPages
Protected Member Functions
size_t OnChartAppended (const V_CHARTDATAD &vChartData)
size_t OnChartTruncated (const V_CHARTDATAD &vChartData)
size_t OnChartDataReplaced (const V_CHARTDATAD &vChartData, bool bHasCellsMap=false)
void CalcLayout (void)
void CalcLayout (int flags, size_t dataItOffs=0)
void CreateChildren (void)
string_t GetDataIDStr (size_t dataID)
string_t GetDataValStr (double val, int precision)
string_t GetTableHeader (void)
size_t DataItemFromMousePnt (CPoint pnt, PointD &dataPntD, RectF &itemRF)
bool RowRectFromDataID (size_t dataID, RectF &rowRF)
void DrawPageHeader (float offsetX, Graphics *grPtr, size_t pageNmb, float dpiRatio)
float DrawTableHeader (float offsetX, float offsetY, Graphics *grPtr, float dpiRatio)
size_t DrawDataPage (size_t dataStartID, float tableOffsX, float tableOffsY, Graphics *grPtr, float dpiRatio)
void DrawSelCells (Graphics *grPtr)
Protected Attributes
int m_chartIdx
int m_precision
int m_precisionY
string_t m_label
string_t m_header
string_t m_labelX
string_t m_labelY
val_label_str_fn m_pXLabelStrFn
val_label_str_fn m_pYLabelStrFn
Color m_bkColor
Color m_selColor
Color m_textColor
RectF m_headerRF
RectF m_rowRF
RectF m_nmbRF
RectF m_dataYRF
RectF m_dataXRF
float m_offsX
float m_offsY
float m_deltaX
float m_deltaY
size_t m_page
size_t m_cols
size_t m_rows
size_t m_currPageID
float m_dpiRatio
CPageCtrl m_leftEnd
CPageCtrl m_leftArr
CPageCtrl m_rightArr
CPageCtrl m_rightEnd
CButton m_btnPrint
CButton m_btnClose
Detailed Description
Definition at line 48 of file ChartDataView.h.
Constructor & Destructor Documentation
CChartDataView::CChartDataView ()
Definition at line 131 of file ChartDataView.cpp.
CChartDataView::~CChartDataView () virtual
Definition at line 144 of file ChartDataView.cpp.
Member Function Documentation
void CChartDataView::CalcLayout (void) protected
Definition at line 496 of file ChartDataView.cpp.
References DATA_ENDOFFS, and DR_SPACE.
void CChartDataView::CalcLayout (int flags, size_t dataItOffs = 0) protected
Definition at line 587 of file ChartDataView.cpp.
References DATA_ENDOFFS, DR_SPACE, F_DSIZE, F_NAMEX, F_NAMEY, F_VALX, and F_VALY.
size_t CChartDataView::ChangeDataPage (int pageNmb)
Definition at line 869 of file ChartDataView.cpp.
void CChartDataView::CreateChildren (void) protected
Definition at line 699 of file ChartDataView.cpp.
References IDC_DV_BTNCLOSE, IDC_DV_BTNPRINT, IDC_DV_LEFTARR, IDC_DV_LEFTENDARR, IDC_DV_RIGHTARR, and IDC_DV_RIGHTENDARR.
size_t CChartDataView::DataItemFromMousePnt (CPoint pnt, PointD & dataPntD, RectF & itemRF) protected
Definition at line 780 of file ChartDataView.cpp.
References in_range().
size_t CChartDataView::DrawDataPage (size_t dataStartID, float tableOffsX, float tableOffsY, Graphics * grPtr, float dpiRatio) protected
Definition at line 974 of file ChartDataView.cpp.
References DATA_ENDOFFS.
void CChartDataView::DrawPageHeader (float offsetX, Graphics * grPtr, size_t pageNmb, float dpiRatio) protected
Definition at line 917 of file ChartDataView.cpp.
void CChartDataView::DrawSelCells (Graphics * grPtr) protected
Definition at line 1062 of file ChartDataView.cpp.
float CChartDataView::DrawTableHeader (float offsetX, float offsetY, Graphics * grPtr, float dpiRatio) protected
Definition at line 934 of file ChartDataView.cpp.
References DATA_ENDOFFS.
size_t CChartDataView::GetCurrPageNmb (void) const inline
Definition at line 60 of file ChartDataView.h.
string_t CChartDataView::GetDataIDStr (size_t dataID) protected
Definition at line 759 of file ChartDataView.cpp.
string_t CChartDataView::GetDataValStr (double val, int precision) protected
Definition at line 769 of file ChartDataView.cpp.
size_t CChartDataView::GetPagesNmb (void) const inline
Definition at line 59 of file ChartDataView.h.
string_t CChartDataView::GetTableHeader (void) protected
Definition at line 852 of file ChartDataView.cpp.
void CChartDataView::InitParams (const CChart * chartPtr, bool bClearMap, const CChartContainer * pHost)
Definition at line 148 of file ChartDataView.cpp.
References CChartContainer::GetAxisXName(), CChart::GetAxisYName(), CChart::GetChartIdx(), CChart::GetChartName(), CChartContainer::GetContainerPrecisionX(), CChartContainer::GetLabXValStrFnPtr(), CChart::GetLabYValStrFnPtr(), CChart::GetPrecisionY(), and CChart::m_vDataPnts.
size_t CChartDataView::OnChartAppended (const V_CHARTDATAD & vChartData) protected
Definition at line 341 of file ChartDataView.cpp.
size_t CChartDataView::OnChartDataReplaced (const V_CHARTDATAD & vChartData, bool bHasCellsMap = false) protected
Definition at line 398 of file ChartDataView.cpp.
size_t CChartDataView::OnChartTruncated (const V_CHARTDATAD & vChartData) protected
Definition at line 369 of file ChartDataView.cpp.
size_t CChartDataView::PrintData (size_t nPage, Graphics * grPtr)
Definition at line 1082 of file ChartDataView.cpp.
size_t CChartDataView::RefreshSelCells (void)
Definition at line 459 of file ChartDataView.cpp.
References in_range(), CChartContainer::UpdateDataViewPnts(), and PointT< T >::X.
bool CChartDataView::RowRectFromDataID (size_t dataID, RectF & rowRF) protected
Definition at line 828 of file ChartDataView.cpp.
References in_range().
void CChartDataView::ShowWaitMessage (int chartIdx, size_t newSize)
Definition at line 896 of file ChartDataView.cpp.
size_t CChartDataView::UpdateDataIdx (void)
Definition at line 415 of file ChartDataView.cpp.
References in_range(), CChartContainer::UpdateDataViewPnts(), and PointT< T >::X.
bool CChartDataView::UpdateParams (const CChart * chartPtr, int flagsData)
Definition at line 195 of file ChartDataView.cpp.
References CChartContainer::DestroyChartDataView(), F_APPEND, F_DSIZE, F_HASCELLSMAP, F_NAMEX, F_NAMEY, F_NODATACHANGE, F_REPLACE, F_TRUNCATE, F_VALX, F_VALY, CChartContainer::GetAxisXName(), CChart::GetAxisYName(), CChart::GetChartIdx(), CChart::GetChartName(), CChartContainer::GetContainerPrecisionX(), CChartContainer::GetLabXValStrFnPtr(), CChart::GetLabYValStrFnPtr(), CChart::GetPrecisionY(), CChart::HasData(), and CChart::m_vDataPnts.
Member Data Documentation
Color CChartDataView::m_bkColor protected
Definition at line 121 of file ChartDataView.h.
CButton CChartDataView::m_btnClose protected
Definition at line 155 of file ChartDataView.h.
CButton CChartDataView::m_btnPrint protected
Definition at line 154 of file ChartDataView.h.
int CChartDataView::m_chartIdx protected
Definition at line 104 of file ChartDataView.h.
RectF CChartDataView::m_clipRF
Definition at line 129 of file ChartDataView.h.
size_t CChartDataView::m_cols protected
Definition at line 142 of file ChartDataView.h.
size_t CChartDataView::m_currPageID protected
Definition at line 144 of file ChartDataView.h.
RectF CChartDataView::m_dataXRF protected
Definition at line 135 of file ChartDataView.h.
RectF CChartDataView::m_dataYRF protected
Definition at line 134 of file ChartDataView.h.
float CChartDataView::m_deltaX protected
Definition at line 139 of file ChartDataView.h.
float CChartDataView::m_deltaY protected
Definition at line 140 of file ChartDataView.h.
float CChartDataView::m_dpiRatio protected
Definition at line 148 of file ChartDataView.h.
float CChartDataView::m_fontHeight
Definition at line 126 of file ChartDataView.h.
string_t CChartDataView::m_fontName
Definition at line 125 of file ChartDataView.h.
string_t CChartDataView::m_header protected
Definition at line 108 of file ChartDataView.h.
float CChartDataView::m_headerFontHeight
Definition at line 127 of file ChartDataView.h.
RectF CChartDataView::m_headerRF protected
Definition at line 131 of file ChartDataView.h.
string_t CChartDataView::m_label protected
Definition at line 107 of file ChartDataView.h.
string_t CChartDataView::m_labelX protected
Definition at line 109 of file ChartDataView.h.
string_t CChartDataView::m_labelY protected
Definition at line 110 of file ChartDataView.h.
CPageCtrl CChartDataView::m_leftArr protected
Definition at line 151 of file ChartDataView.h.
CPageCtrl CChartDataView::m_leftEnd protected
Definition at line 150 of file ChartDataView.h.
MAP_SELPNTSD CChartDataView::m_mapSelCells
Definition at line 119 of file ChartDataView.h.
RectF CChartDataView::m_nmbRF protected
Definition at line 133 of file ChartDataView.h.
size_t CChartDataView::m_nPages
Definition at line 146 of file ChartDataView.h.
float CChartDataView::m_offsX protected
Definition at line 137 of file ChartDataView.h.
float CChartDataView::m_offsY protected
Definition at line 138 of file ChartDataView.h.
size_t CChartDataView::m_page protected
Definition at line 141 of file ChartDataView.h.
int CChartDataView::m_precision protected
Definition at line 105 of file ChartDataView.h.
int CChartDataView::m_precisionY protected
Definition at line 106 of file ChartDataView.h.
val_label_str_fn CChartDataView::m_pXLabelStrFn protected
Definition at line 111 of file ChartDataView.h.
val_label_str_fn CChartDataView::m_pYLabelStrFn protected
Definition at line 112 of file ChartDataView.h.
CPageCtrl CChartDataView::m_rightArr protected
Definition at line 152 of file ChartDataView.h.
CPageCtrl CChartDataView::m_rightEnd protected
Definition at line 153 of file ChartDataView.h.
RectF CChartDataView::m_rowRF protected
Definition at line 132 of file ChartDataView.h.
size_t CChartDataView::m_rows protected
Definition at line 143 of file ChartDataView.h.
Color CChartDataView::m_selColor protected
Definition at line 122 of file ChartDataView.h.
Color CChartDataView::m_textColor protected
Definition at line 123 of file ChartDataView.h.
V_CHARTDATAD CChartDataView::m_vDataPnts
Definition at line 115 of file ChartDataView.h.
V_ROWS CChartDataView::m_vRows
Definition at line 118 of file ChartDataView.h.
V_VALSTRINGS CChartDataView::m_vStrX
Definition at line 116 of file ChartDataView.h.
V_VALSTRINGS CChartDataView::m_vStrY
Definition at line 117 of file ChartDataView.h.
The documentation for this class was generated from the following files:
C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/ChartDataView.h
C:/VS2010/Projects/ChartCtrlLib/ChartCtrlLib/ChartDataView.cpp