//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LineTrackApp.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LINETRACKAPP_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDC_CUSTOM1                     1000
#define IDC_EDIT1                       1001
#define IDC_CUSTOM2                     1002
#define IDC_CUSTOM3                     1003
#define IDC_EDIT2                       1004
#define IDC_EDIT3                       1005
#define IDC_CUSTOM4                     1006
#define IDC_CUSTOM5                     1007
#define IDC_EDIT4                       1008
#define IDC_EDIT5                       1009
#define IDC_SPIN1                       1012
#define IDC_CUSTOM6                     1015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
