// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "thumbctl.h"

/////////////////////////////////////////////////////////////////////////////
// CThumbCtl

IMPLEMENT_DYNCREATE(CThumbCtl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CThumbCtl properties

/////////////////////////////////////////////////////////////////////////////
// CThumbCtl operations

BOOL CThumbCtl::displayFile(LPCTSTR bsFileName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		bsFileName);
	return result;
}

BOOL CThumbCtl::haveThumbnail()
{
	BOOL result;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString CThumbCtl::FreeSpace()
{
	CString result;
	InvokeHelper(0x3, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CThumbCtl::UsedSpace()
{
	CString result;
	InvokeHelper(0x4, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString CThumbCtl::TotalSpace()
{
	CString result;
	InvokeHelper(0x5, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}
