#if !defined(AFX_THUMBCTL_H__C3E127D1_BDCB_11D3_A186_00902735233D__INCLUDED_)
#define AFX_THUMBCTL_H__C3E127D1_BDCB_11D3_A186_00902735233D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CThumbCtl wrapper class

class CThumbCtl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CThumbCtl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1d2b4f40, 0x1f10, 0x11d1, { 0x9e, 0x88, 0x0, 0xc0, 0x4f, 0xdc, 0xab, 0x92 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL displayFile(LPCTSTR bsFileName);
	BOOL haveThumbnail();
	CString FreeSpace();
	CString UsedSpace();
	CString TotalSpace();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_THUMBCTL_H__C3E127D1_BDCB_11D3_A186_00902735233D__INCLUDED_)
