
#pragma once


#define SLN_HEADER						"Microsoft Visual Studio Solution File"
#define SLN_PROJECT						"Project("
#define SLN_ENDPROJECT					"EndProject"
#define SLN_GLOBALSECTION				"GlobalSection("
#define SLN_ENDGLOBALSECTION			"EndGlobalSection"
#define SLN_SECTIONCONFIGURATION		"SolutionConfiguration"
#define SLN_SECTIONDEPENDENCIES			"ProjectDependencies"
#define SLN_SECTIONPROJECTCONFIGURATION "ProjectConfiguration"
#define SLN_SECTIONEXTENSGLOBALS		"ExtensibilityGlobals"
#define SLN_SECTIONEXTENSADDINS			"ExtensibilityAddIns"

#define XMLNODE_VISUALSTUDIOPROJECT		"VisualStudioProject"
#define XMLNODE_CONFIGURATION			"Configuration"
#define XMLNODE_TOOL					"Tool"
#define XMLNODE_FILTER					"Filter"
#define XMLNODE_FILES					"Files"
#define XMLNODE_FILE					"File"
#define XMLNODE_FILECONFIGURATION		"FileConfiguration"
#define XMLATTRIB_NAME					"Name"
#define XMLATTRIB_SCCPROJECTNAME		"SccProjectName"
#define XMLATTRIB_SCCPROJECTPATH		"SccLocalPath"
#define XMLATTRIB_TARGETTYPE			"ConfigurationType"
#define XMLATTRIB_PREPROCDEFINITIONS	"PreprocessorDefinitions"
#define XMLATTRIB_RELATIVEPATH			"RelativePath"
#define XMLATTRIB_FULLPATH				"FullPath"
#define XMLATTRIB_SUBSYSTEM				"SubSystem"

#define VCCOMPILERTOOL					"VCCLCompilerTool"
#define VCLIBRARIANTOOL					"VCLibrarianTool"
#define VCLINKERTOOL					"VCLinkerTool"
#define VCRESOURCECOMPILERTOOL			"VCResourceCompilerTool"
#define VCMIDLTOOL						"VCMidlTool"
#define VCBSCMAKETOOL					"VCBscMakeTool"
#define VCPREBUILDEVENTTOOL				"VCPreBuildEventTool"
#define VCPRELINKEVENTTOOL				"VCPreLinkEventTool"
#define VCPOSTBUILDEVENTTOOL			"VCPostBuildEventTool"
#define VCCUSTOMBUILDTOOL				"VCCustomBuildTool"
#define VCNMAKETOOL						"VCNMakeTool"
#define VCDEBUGSETTINGSTOOL				"VCDebugSettingsTool"