//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Wzd.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_WZDTYPE                     129
#define IDD_MENU_DIALOG                 130
#define IDB_BITMAP1                     131
#define IDR_WZD_MENU                    132
#define IDC_MENU_STATIC                 1002
#define ID_POPUP_WZD1                   32771
#define ID_POPUP_WZD2                   32772
#define ID_POPUP_WZD3                   32773
#define ID_POPUP_WZD4                   32774
#define ID_POPUP_WZD5                   32775
#define ID_POPUP_WZD6                   32776
#define ID_POPUP_WZD7                   32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
